### ISSUE TITLE
Documentation on routes and switches

### ISSUE THREAD

**Issue by doonhammer** [openvswitch/ovn-kubernetes#124]
I think I have it almost figured out but it would make it a lot easier if there was a diagram showing the topology of the switches and routers in a k8s cluster. I have sfc working for the vagrant setup but it was mostly trial and error to figure out what was connected each node. Also some documentation on the naming convention :-) 

Regards

John

**Comment by shettyg** [comment]
@doonhammer The diagram linked here, is the closest we have right now:
http://i.imgur.com/m7hcHhn.png

**Comment by shettyg** [comment]
@doonhammer 

I think github replies strips off the attachments. Feel free to unicast me.
