### ISSUE TITLE
ovn-kubernetes doesn't handle nodeport services correctly

### ISSUE THREAD

**Issue by sjpotter** [openvswitch/ovn-kubernetes#128]
It appears that ovn-kubernetes only creates a nodeport on the gateway node(s), it doesn't setup a load balancer for the cluster ip that is created for it.

can see the code here

https://github.com/openvswitch/ovn-kubernetes/blob/6c87f60ba883b5e879c9e16f1a9310cb54ab61fb/ovn_k8s/modes/overlay.py#L420-L429

see Kubernetes documentation one nodeport

https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport

"Note that this Service will be visible as both <NodeIP>:spec.ports[*].nodePort and spec.clusterIp:spec.ports[*].port."

it should be the equivalent of a case statement with a fall through from nodeport to cluster ip (and if ever support load balancer type, that would be the top of the fall through), this meas restructuring the code a bit, as can't need to determine port individually within each of the case statements.

**Comment by shettyg** [comment]
@sjpotter You are right. I was not sure how useful it is to create another east-west load-balancing service for a nodeport. It is probably not hard to add the gap though. I will look into it.

**Comment by sjpotter** [comment]
I don't think it should be that hard, you just create 2 load balancers. 

something along the lines of 

if !NodePort && !ClusterIP
    return 

if NodePort
    add_node_port()

add_cluster_ip()

the functionality of add node_port and add_cluster_ip are already there as _create_gateways_vip and _create_cluster_vip

it's not a single port for both of them, so a small refactor has to occur, but should be pretty straightforward.
