### ISSUE TITLE
Dependencies should specify required package versions

### ISSUE THREAD

**Issue by geo-turcsanyi** [openvswitch/ovn-kubernetes#131]
Environment:
Centos7
Python 2.7, pip 8.1.2

Action:
Trying to create the following pod: https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/vault.yaml

Kubectl gives a plain "FailedSync Error syncing pod", kubelet is more specific though.

Traceback (most recent call last):
  File "/opt/cni/bin/ovn_cni", line 28, in <module>
    from ovn_k8s.common import kubernetes
  File "/usr/lib/python2.7/site-packages/ovn_k8s/common/kubernetes.py", line 16, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'
E0719 15:49:56.378117   12558 cni.go:312] Error deleting network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input

A simple yum install -y python-requests will solve this, but it is quite annoying to see and look into the root cause and the ovn specific logs do not give any info on the root cause.

**Comment by shettyg** [comment]
@geo-turcsanyi 

The file here has the "requests" as a requirement. 
https://github.com/openvswitch/ovn-kubernetes/blob/master/requirements.txt#L3

"pip install ." should have installed requests. The question is why it did not in your case. Or if it did, may be it installed a version that does not have the urllib3. 

Now CNI plugin of OVN itself is tied to kubelet as that is the only one that calls it (it is not a daemon for OVN to log). Any error is returned back to kubelet. So it is fair that the error message is seen in kubelet.

**Comment by geo-turcsanyi** [comment]
@shettyg Thanks for the quick overview on how the components work, it makes a bit more sense now.

In regards to the dependencies, it did install requests, only an earlier version, and yes, it did seem the case where it didn't have urllib3. And a correction, not  yum install -y python-requests fixed this, but pip install requests --upgrade.

**Comment by shettyg** [comment]
Frankly, I don't understand pip enough to point out why it did not install the latest "requests" package. One possibility is that your pip itself was a older version which had a bug wherein it installs local copies instead of grabbing things from the internet.
