### ISSUE TITLE
go-controller does not sync deleted events

### ISSUE THREAD

**Issue by shettyg** [openvswitch/ovn-kubernetes#133]
Reproduction:

* Start go-controller
* Create a pod -> This creates a logical port in OVN
* Stop go-controller
* Delete a pod
* Start go-controller after some time -> This does not delete the logical port in OVN.

go-controller should delete the logical port in OVN.

**Comment by shettyg** [comment]
@rajatchopra

**Comment by rajatchopra** [comment]
Fixed by #165
