### ISSUE TITLE
Support service type ClusterIP

### ISSUE THREAD

**Issue by kshafiee** [openvswitch/ovn-kubernetes#155]

**Comment by shettyg** [comment]
We do support ClusterIP. But there is a gap wherein if you create a nodeport, we do not create clusterIP. Is that what you meant?

**Comment by kshafiee** [comment]
I can see that ClusterIP is supported. But, even though PodIP (EndpointIP) is reachable, ClusterIP is not reachable: 
![image 1](https://user-images.githubusercontent.com/7294758/30722916-9799b1a2-9ee8-11e7-990f-ab357dadb4c3.png)

**Comment by shettyg** [comment]
@kshafiee 

They do work. I am trying to understand why it is not working in your case. What is the netmask for 10.100.65.247? One possibility is that In this case,there is no route to 10.100.65.247 from your host. 

What is the minion or master subnet for this host? When we run the master-init/minion-init, we give a cluster wide subnet. Is your cluster IP provided in the same large subnet? 

You can do a 'route -n' and that should give a hint.

**Comment by shettyg** [comment]
You can also try to reach the clusterIP from inside a pod. Does that work?

**Comment by kshafiee** [comment]
@shettyg ClusterIP works on the master node, but not on the slave node. Neither from inside the pod

**Comment by shettyg** [comment]
@kshafiee 

Summary:
You need --master-switch-subnet to be a subnet of --cluster-ip-subnet. You also need the clusterIP provided by k8s to be also a subnet of --cluster-ip-subnet.

Details:
======
What we do is that, on each node, we create a OVS internal port (or a host interface) and assign it an IP address in the subnet assigned for that node. For e.g., if --master-switch-subnet is 192.168.1.0/24, then we assign 192.168.1.2/24 to that host interface. And 192.168.1.1/24 would be a OVN virtual router IP address. We Also add a route entries on that host - which say that 192.168.0.0/16 is reachable via 192.168.1.1/24. So if you do a curl 192.168.X.Y from host, it enters the OVN logical pipeline.

Now, if the clusterIP for k8s is also a subnet of 192.168.0.0/16, the route entry that we added is automatically valid for a VIPs too. i.e you can access a VIP from a host. But irrespective of this, a VIP should always be accessible from inside the POD.  

You can either create your clusterIP to be one of the subnets of 192.168.0.0/16 or you can add a manual route that says that your cluster subnet is reachable from 192.168.1.1/24 from master and 192.168.2.1/24 from minion1, 192.168.3.1/24 from minion2 etc

Once you get the above correctly, let me know how it goes. Also, let me know whether your pod from which you are trying to access clusterIP is in a windows node or a linux node.

**Comment by shettyg** [comment]
I would also suggest to create a services backing pods as endpoints for your testing to remove some other possible issues.

**Comment by kshafiee** [comment]
Thanks @shettyg 

on master I have:
ovn-k8s-overlay master-init   --cluster-ip-subnet="10.0.0.0/8"   --master-switch-subnet="10.244.1.0/24"   --node-name="$HOSTNAME"

on slave I have:
windows-init.exe windows-init --node-name $HOSTNAME --minion-switch-subnet "10.244.9.0/24" --cluster-ip-subnet "10.0.0.0/8"

On master I can access both PodIP & ServiceIP:
![image](https://user-images.githubusercontent.com/7294758/30777223-b0a334ce-a06a-11e7-9471-0033c851021e.png)

But, inside the Pod ServiceIP is not reachable (I can only access PodIP):
![image](https://user-images.githubusercontent.com/7294758/30777272-e1644e80-a06b-11e7-80eb-bdbf3963e023.png)

The routing table inside the pod is (no entry for 10.0.0.0/8):
![image](https://user-images.githubusercontent.com/7294758/30777277-10828c68-a06c-11e7-8b13-bb2111359f59.png)

However, the serviceIP is not even reachable on the slave node. The routing table on the slave node is (there's an entry for 10.0.0.0/8):
![image](https://user-images.githubusercontent.com/7294758/30777296-4c0d1384-a06c-11e7-8b27-f4c3a1b49e29.png)

**Comment by kshafiee** [comment]
BTW, EndpointIP (PodIP) and ServiceIP for the nginx are:
![image](https://user-images.githubusercontent.com/7294758/30777319-aa2a4734-a06c-11e7-96d3-24e880b04a5d.png)

**Comment by shettyg** [comment]
@alinbalutoiu @aserdean

Any tips on how to debug this? Looks like NAT is not taking place on Windows host.

**Comment by aserdean** [comment]
We added some stateless NAT-ing when we implemented the python agent that emulates the CNI plugin.

@alinbalutoiu is working on removing the agent and implementing a CNI plugin.

We will be back with updates when we address this issue.

**Comment by aserdean** [comment]
@shettyg this should be closed by PR: https://github.com/openvswitch/ovn-kubernetes/commit/ace1c6bb56f72b6024bd3f2d4b2782504791b469 . Sorry it took so much to send the PR.
