### ISSUE TITLE
go-controller: ovnkube init master/node failed

### ISSUE THREAD

**Issue by feiskyer** [openvswitch/ovn-kubernetes#159]
ovnkube is depending on systemctl to start openvswitch and ovn services, but they are not exist on all systems (e.g. openvswitch 2.8.0 on Ubuntu 16.04). In this case, `ovnkube --init-master` and `ovnkube --init-node` will both fail because openvswitch/ovn can't start.

Any ideas on this? @shettyg

**Comment by rajatchopra** [comment]
Yes, we need to address this issue for different init systems. Most of this has to go as part of installation procedure instead really. So vagrant/Ansible etc should handle this appropriately.
Maybe we could use ovs_ctl script instead meantime.

**Comment by shettyg** [comment]
We do have debian packages for ovn. Ubuntu itself does not let you select specific version. We can use the ovn debian packages hosted by the nz university.

**Comment by shettyg** [comment]
What we could do for the time being (till ubuntu starts using more recent OVN packages) is to add:
1. In install_ovn.sh:
https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-master.sh#L33-L36
https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-master.sh#L55

2. In master.go and node.go
Check whether it is rhel or debian. 

In case of debian:
Restart ovn-controller after setting up the OVSDB with IP addresses with a "service ovn-host restart". We don't need to to restart for "ovn-central".

@feiskyer 
Is this something you want to try?
