### ISSUE TITLE
cannot create pod success

### ISSUE THREAD

**Issue by xidianby0911** [openvswitch/ovn-kubernetes#177]
after i deploy the ovn-k8s plugin, i create a pod,but pod's status always being containercreating. i use command "systemctl status kubelet -l ",there are some errors shown:
ovs ovn-k8s-cni-overlay | ERR | failed to get pod annotation:('Connection aborted,' Connection refused)
ovn-k8s-cni-overlay | ERR | failed to get pod annotation:(Connection error(111,  'Connection refused'))

ovs ovn-k8s-cni-overlay | ERR | failed to get pod annotation:(Connection refused)
error adding network:
error while adding to cni network:
runpodsandbox from runtime service failed:networkplugin cni failed to set up pod "kube-dns-545bc4bfd4-6lh4l_kube-system"netwok:
createpodsandbox for pod "kube-dns-  "failed: rpc error: code = unknown desc = networkplugin cni failed to set up "kube-system"netwok:

**Comment by rajatchopra** [comment]
Can you get the output of 'ovs-vsctl get  Open_vSwitch . external_ids' from one of the nodes? The cni plugin is not able to reach the apiserver it seems.

**Comment by xidianby0911** [comment]
My ovs version is 2.8.1,can it work well with ovn plugin?

**Comment by rajatchopra** [comment]
> My ovs version is 2.8.1,can it work well with ovn plugin?

Yes, that version is good. Better even. Could you get the output of 'ovs-vsctl get Open_vSwitch . external_ids'? I suspect some setup issues.

**Comment by xidianby0911** [comment]
The output of 'ovs-vsctl get Open_vSwitch. external_ids' was:
｛hostname=localhost,"k8s-ca-certificate =",ovn-encap-ip=192.168.1.7,ovn-encap-type=stt,ovn-nb=tcp:192.168.1.6：6641,ovn-remote=tcp:192.168.1.6:6642,run=/usr/local/var/run/openvswitch…｝
But my hostname is k8s.node1. Does this affect normal work?

**Comment by xidianby0911** [comment]
My k8s-api-server=10.10.1.2:8080

**Comment by xidianby0911** [comment]
The output of 'ovs-vsctl get Open_vSwitch. external_ids' was:
｛hostname=localhost,"k8s-api-server=10.10.1.2:8080,k8s-api-token =…,k8s-ca-certificate =…",ovn-encap-ip=192.168.1.7,ovn-encap-type=stt,ovn-nb=tcp:192.168.1.6：6641,ovn-remote=tcp:192.168.1.6:6642,run=/usr/local/var/run/openvswitch…｝
But my hostname is k8s.node1. Does this affect normal work?

**Comment by shettyg** [comment]
We have moved to golang now. Closing all python bugs.
