### ISSUE TITLE
can i appoint the pod ip when create the pod 

### ISSUE THREAD

**Issue by xidianby0911** [openvswitch/ovn-kubernetes#179]
Using the ovn plugin, can i appoint the pod ip witch i create? or modify the pod ip after i create it?

**Comment by rajatchopra** [comment]
Not currently. 
But perhaps we can, as long as the request is within the range of the CIDR assigned to the logical switch.

Could you elaborate on the use case? The idea in kubernetes is to use a service IP instead because pods are considered disposable (cattle).
