### ISSUE TITLE
The CNI plugin should use the api server secure port

### ISSUE THREAD

**Issue by salv-orlando** [openvswitch/ovn-kubernetes#18]
Leveraging the insecure port (default 8080) is easy and simplifies implementation.
In order to support scenarios just a bit closer to production, the CNI plugin should use the secure port (default 6643).

This issue will deal with identifying the authentication methods the CNI plugin must support and defining the changes in the CNI plugin itself.

**Comment by salv-orlando** [comment]
Shalle we close the issue here or do we want to use it to track usage of more sophistitcated methods such as service accounts (I think one might use them when running the watcher in a pod)?

**Comment by shettyg** [comment]
Lets close it. And open more particular use cases as separate issue.
