### ISSUE TITLE
master node was notready 

### ISSUE THREAD

**Issue by xidianby0911** [openvswitch/ovn-kubernetes#181]
after i deploy the ovn-k8s plugin,the master node's status was notready, the minion node's status was ready. In this case, could the k8s colony work well?

**Comment by rajatchopra** [comment]
Can you capture the logs shown by the kubelet on the master node? Also, if you could get the node object's status? Using kubectl get node ${master-node-name} -o yaml and then paste the Status field.

**Comment by shettyg** [comment]
In master node, we don't add CNI plugin. We assumed that you don't run kubelet on master. It looks like that may be wrong.

**Comment by jbiel** [comment]
I'm prototyping a cluster based on `kubeadm` and the master(s) run kubelet.

**Comment by nlowe** [comment]
I was able to get my `kubeadm` generated master deployed by ensuring the CNI config is present:

```bash
sudo mkdir -p /etc/cni/net.d
echo '{"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay"}' | sudo tee /etc/cni/net.d/10-ovn-kubernetes.conf
sudo systemctl restart kubelet
```

**Comment by shettyg** [comment]
This is fixed in master node. One needs to pass "init-node" as well as "init-master" to ovnkube as described in the README file.
