### ISSUE TITLE
No way to remove gateway routers

### ISSUE THREAD

**Issue by rajatchopra** [openvswitch/ovn-kubernetes#242]
There should be a utility to undo a 'gateway-init' on a node. Specifically useful when nodes are taken out of the clusters.
e.g. the breth0 should be destroyed and eth0 be restored as a regular interface on the host

**Comment by alinbalutoiu** [comment]
I think this is partially addressed by https://github.com/openvswitch/ovn-kubernetes/pull/298
Leaving that here to make it easier to check the progress for this issue.

**Comment by rajatchopra** [comment]
@alinbalutoiu Correct. The big portion is done #298. The only remaining step is to remove the actual logical router and ext-switch alongwith the ls-port to join switch.

**Comment by shettyg** [comment]
This is done now on master.
