### ISSUE TITLE
K8s Master node as worker node

### ISSUE THREAD

**Issue by girishmg** [openvswitch/ovn-kubernetes#295]
If we want to configure K8s master node as a worker node, then one would  execute ovnkube as below

> $ sudo ovnkube --net-controller --cluster-subnet 192.168.0.0/16 --init-master=`hostname` --init-node=`hostname`......

ovnkube then configures the node for master first and then configures the node for worker next.
```
	if master != "" {
                        <snip>
			err := clusterController.StartClusterMaster(master)
                        <snip>
		}

		if node != "" {
                        <snip>
			err := clusterController.StartClusterNode(node)
                        <snip>
		}
```

First time around in StartClusterMaster we set aside 192.168.0.0/24 for master node, however we don't add that subnet as an annotation to the master node. Then we loop through next set of subnets -- 192.168.1.0/24, 192.168.2.0/24, and so on -- for other nodes (including the master). In this case, the master node is annotated with 192.168.1.0/24. 

Master now has two subnets -- 192.168.0.0/24 (not added as Node annotation) and 192.168.1.0/24 (added as Node annotation). Now, 

-- StartClusterMaster()`SetupMaster() sets up master using 192.168.0.0./24
-- StartCluster Node()`CreateManagementPort() sets up master again using 192.168.1.0/24

The code doesn't error out thanks to the usage of --may-exists and --if-exists to ovn-nbctl command. 
The 2nd invocation using 192.168.1.0/24 over-writes everything except for the gateway IP for the subnet and it will still be 192.168.0.1/24 (from the 1st subnet). It doesn't overwrite the gateway IP because of the code here and routerMac will be non-empty 2nd time around.

```
	if routerMac == "" {
                <snip>
		_, stderr, err = util.RunOVNNbctl("--may-exist", "lrp-add", clusterRouter, "rtos-"+nodeName, routerMac, routerIPMask)
                <snip>
	}
```
This breaks everything.

**Comment by rajatchopra** [comment]
In the light of issues addressed in #293 as well, I would like to propose that master should not create management port at all. It should only create the logical router.
Then, on the master node, we should run two processes: 'ovnkube --init-master -net-controller' and 'ovnkube --init-node' separately. This would be a cleaner cut I believe.

**Comment by rajatchopra** [comment]
@girishmg As a work-around to this problem, you need to start ovnkube with different names given to init-master vs init-node. So, two hostnames in fact. 
The name given to 'init-node' should match the node's name in kubernetes. But the master's hostname could be different.

**Comment by shettyg** [comment]
I sent https://github.com/openvswitch/ovn-kubernetes/pull/322 to fix this.
