### ISSUE TITLE
Hyper-V is a hard requirement for Openvswitch 2.9.0 on Windows?

### ISSUE THREAD

**Issue by jbiel** [openvswitch/ovn-kubernetes#337]
Hello, is it possible to use k8s/OVN on Windows without Hyper-V? If not, will it be possible in the near future? We are running on Google Cloud (can't install Hyper-V) but I'm stuck at the point of trying to tie bridges/HNS adapters together with `ovs-vsctl`. None of the VMSwitch cmdlets are working without Hyper-V installed of course.

I've tried [these instructions](https://github.com/alinbalutoiu/kubernetes.github.io/blob/92a12e605199070088b42b3a711b082a0fdc9cc1/docs/getting-started-guides/windows/index.md) as well as the ["official" instructions](https://kubernetes.io/docs/getting-started-guides/windows/). The latter seem to be geared towards 2016 RTM; we're using 1709+ and no HNSTransparent NetAdapter is created by Docker. The adapter created shows up from `Get-HnsNetwork` but I don't know if that's usable. Thanks in advance for any info/help with this.

More environment info:
* Platform: Google Cloud (Hyper-V installation is impossible)
* Windows versions: 1709 & 1803 (I'm trying both)
* Openvswitch version: 2.9.0 (manually built because the 2.7.0 MSI installer from Cloudbase won't install; likely due to Hyper-V dependency)
* Kubernetes: 1.10.2
* ovnkube is functioning on Linux nodes; pod networking is all good

```
PS C:\k> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
68a622b2b825        external            transparent         local
371b186ea805        nat                 nat                 local
faa06f45ec8a        none                null                local

PS C:\k> (Get-HnsNetwork)[1]
ActivityId             : 900321b2-4f4f-4a47-b316-63d9af5b583c
CurrentEndpointCount   : 0
Extensions             : {@{Id=e7c3b2f0-f3c5-48df-af2b-10fed6d72e7a; IsEnabled=False; Name=Microsoft Windows Filtering Platform}, @{Id=e9b59cfa-2be1-4b21-828f-b6fbdbddc017; IsEnabled=False; Name=Microsoft Azure VFP Switch Extension},
                         @{Id=ea24cd6c-d17a-4348-9190-09f0d5be83dd; IsEnabled=False; Name=Microsoft NDIS Capture}}
ID                     : bdcf1701-df23-4247-8d41-c6c28894c587
LayerResources         : @{AllocationOrder=3; Allocators=System.Object[]; ID=88f78372-e1c2-4226-8be9-6252503f20b1; PortOperationTime=0; State=1; SwitchOperationTime=0; VfpOperationTime=0}
LayeredOn              : 22cce0f6-d1c0-41a3-93d3-5926adf28bf7
MacPools               : {@{EndMacAddress=00-15-5D-A1-FF-FF; StartMacAddress=00-15-5D-A1-F0-00}}
MaxConcurrentEndpoints : 0
Name                   : 68a622b2b825aedb783c99ada8071fd2b797ae7a8254ae41f41e9c78eb155e12
NetworkAdapterName     : Ethernet
Policies               : {}
Resources              : @{AllocationOrder=0; ID=900321b2-4f4f-4a47-b316-63d9af5b583c; PortOperationTime=0; State=1; SwitchOperationTime=0; VfpOperationTime=0; parentId=88f78372-e1c2-4226-8be9-6252503f20b1}
State                  : 1
Subnets                : {@{AddressPrefix=192.168.4.0/24; GatewayAddress=192.168.4.1}}
TotalEndpoints         : 0
Type                   : transparent
Version                : 30064771074
```

**Comment by shettyg** [comment]
CC: @alinbalutoiu @aserdean

**Comment by rajatchopra** [comment]
At this point, the Hyper-V is a requirement. But, yes, in the future we are planning to move to pure HNS based stack. Tracker issues will be created soon after some community discussions.

**Comment by aserdean** [comment]
To be short there is no hard dependency on Hyper-V. You can create the ports needed outside of OVS and just plug them afterwards.

The main issue is around OVS ports of type `internal` which for the ease of integration there is code in OVS to handle them: https://github.com/openvswitch/ovs/blob/master/lib/wmi.c#L628-L637 (i.e.).
The problem on 1709+ is that the WMI provider does not exist anymore (although on RTM there was) and one needs to create them via HNS.
That can be done outside of OVS so it is not necessary for OVS to create them. 

I created a PR: https://github.com/openvswitch/ovn-kubernetes/pull/356 to aid people on 1709+. Please note that the work is in progress and I would appreciate feedback.

**Comment by aserdean** [comment]
@jbiel can you please look over the PR and give it a try?

**Comment by aserdean** [comment]
I think we can close this issue because: https://github.com/openvswitch/ovn-kubernetes/pull/356 is merged.

**Comment by rajatchopra** [comment]
This issue can be closed. But it should be noted that the no-hyperv solution will require custom OVS install at this point.

The custom link valid at least at the time of this comment: https://balutoiu.com/ionut/OpenvSwitch.msi

The callback APIs for OVS implemented directly using HNS needs to make it master OVS still.
Target: OVS-2.10
