### ISSUE TITLE
how to enable logging for ovn-k8s-cni-overlay.exe

### ISSUE THREAD

**Issue by mihail-velikov** [openvswitch/ovn-kubernetes#359]
Hello,

We are experiencing a strange issue where the "pause" containers don't stop properly. Trying to delete them with docker rm -f hangs indefinitely. I have checked the logs for kubelet and dockerd on debug but nothing significant can found. The actual application container stops properly in all cases but the "pause" hangs from time to time. Even killing all the processes using task manager does not really help.

Windows version:
C:\cni>ver
Microsoft Windows [Version 10.0.17623.1002]
(this is windows 2019 preview)

PS C:\Windows\system32> docker -v
Docker version master-dockerproject-2018-05-20, build 824ce49a

OVN: 2.7.0

The interesting bit is that with small amount of containers this does not happen that often. Once we increase the containers above 8 on the machine the deletion of a container always fails.

Currently I am suspecting that this might be related with the CNI plugin so I am looking for a way to enable debug on this functionality too. Our current config is:
PS C:\cni> cat 10-ovn-kubernetes.conf
{"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay.exe"}

PS C:\kubernetes> c:\kubernetes\kubelet.exe --cluster-dns="10.32.200.10" --cluster-domain="test.local" --pod-infra-container-image="our_repo/pause-17623"  --resolv-conf="" --kubeconfig=c:\kubernetes\kubeconfig.yaml --network-plugin=cni --cni-bin-dir="C:\\cni" --cni-conf-dir="C:\\cni" --v=4 --cgroups-per-qos=false --enforce-node-allocatable=""  > kubernetes.log 2>&1

PS C:\Program Files\Docker> .\dockerd.exe --config-file C:\ProgramData\docker\config\daemon.json -D > daemon.log 2>&1

To be honest I am not sure what exactly is causing the issue:
- the docker logs contain no errors at all. There are logs for the containers that have stopped properly but no logs for trying to stop the pause containers
- the kubelet complains that it is trying to delete the pod but some containers are still running (which is true). No other exception are logged.

Any ideas would be greatly appreciated.

**Comment by shettyg** [comment]
If you use latest code, you should be able to enable logging in cni plugin (I haven't tried it myself). It works by passing a config file to ovnkube while doing node-init with a argument -config-file. When you do this, it will write  10-ovn-kubernetes.conf with a path to config file (so you can update 10-ovn-kubernetes.conf manually to include this path). When CNI plugin reads 10-ovn-kubernetes.conf, it knows location of config file and then it should get where to log. 

The 10-ovn-kubernetes.conf should look like:
https://github.com/openvswitch/ovn-kubernetes/blob/master/go-controller/pkg/config/cni.go#L28

The config file should itself look something like:

[logging]
loglevel=5
logfile=/var/log/ovnkube.log

**Comment by mihail-velikov** [comment]
Hello shettyg,

I have tried the approach recommended by providing -config-file to the ovnkube command but it does not affect the resulting 10-ovn-kubernetes.conf file. Instead it only saves the output of the ovkube.exe to a log file.

As far as I can see the 10-ovnk-kubernetes.conf looks like a json formatted file:
PS C:\cni> cat .\10-ovn-kubernetes.conf
{"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay.exe"}

Please let me know what kind of variable do I need to set up in this file in order to generate logs for each call. 

Thank you.

Kind Regards,
Mihail Velikov

**Comment by shettyg** [comment]
I tried this on Linux. The contents of 10-ovn-kubernetes.conf:

{"cniVersion":"0.3.1","name":"ovn-kubernetes","type":"ovn-k8s-cni-overlay","ipam":{},"dns":{},"configFilePath":"/home/vagrant/ovnconfig"}

In /home/vagrant/ovnconfig:

[logging]
loglevel=5
logfile=/var/log/ovnkube.log

Now, when I create a pod, the CNI binary logs to "/var/log/ovnkube.log"

**Comment by shettyg** [comment]
This may have been added around late may.

**Comment by mihail-velikov** [comment]
Hello shettyg,

Thank you for the information.  I have upgraded our cluster to the latest version of ovnkube and I am able to collect more detailed logging. 

Thanks a lot!

Kind Regards,
Mihail Velikov
