### ISSUE TITLE
expose nodeport on multiple interfaces

### ISSUE THREAD

**Issue by mihail-velikov** [openvswitch/ovn-kubernetes#380]
Hello,

We have a use case where we would like to expose a nodeport on multiple interfaces on the gateway node. Currently our nodes have 3 network interfaces - EXT (external),  INT(internal), MGMT(management). Due to some internal security policies traffic from the firewall is only allowed to the EXT interface. The INT interface is used for internal communication - our cluster is currently using this interfaces to create the overlay. The MGMT is used for management of the machine (connectivity from the office).

The question is - is it possible to expose a service not only on the INT ip but also on the EXT and if yes - how can we achieve this?

Thank you.

Kind Regards,
Mihail Velikov

**Comment by shettyg** [comment]
@mihail-velikov 

The first question is do you actually need node port on both EXT and INT? Or do you just need it on EXT? 

If both,
OVN lets you do this. But ovn-kubernets likely does not have code to do multiple interfaces on the same host. There are likely small gaps to achieve this. 

Have you tried running kube-proxy too? It should create iptables rules for nodeport. And since we create a mgmt port k8s-$node-name, there is possibility to enter the cluster.

**Comment by shettyg** [comment]
>Have you tried running kube-proxy too? It should create iptables rules for nodeport. And since we create a mgmt port k8s-$node-name, there is possibility to enter the cluster.

You may have to add a NAT rule to change packer src IP to k8s-$node-name IP.

**Comment by mihail-velikov** [comment]
@shettyg 

I got an interesting idea - would it be possible to do a portforwarding using iptables from the EXT interface to the bridge on the INT interface? Currently I would like to expose only our nginx ingress on the EXT interface so I can easily add a step in our ansible playbook to setup this redirect on all gateway nodes.

I tried to setup this using UFW but for some reason it is not working. Here is my config:
1. DEFAULT_FORWARD_POLICY="ACCEPT"  in /etc/default/ufw
2. net.ipv4.ip_forward=1
3. /etc/ufw/before.rules:
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-F
-A PREROUTING -i EXT -p tcp --dport 30080 -j DNAT --to-destination IP_OF_INT_BRIDGE
-A POSTROUTING -s IP_OF_INT_BRIDGE -o EXT -j MASQUERADE
COMMIT

Any ideas?

Btw I noticed an interesting things. Lets say that my linux gateway machines has the overlay running on 192.168.1.5 IP address and my nodeport should be listening on port 30080. If I try to connect to this IP from another host with telnet - it works. When I ssh to this machine and try to connect to the same address it does not work. It seems like it is missing a hairpin NAT and I believe this is the same reason the port forwarding also does not work.

Please excuse me if my explanation is not very good.

Any thoughts would be greatly appreciated.

Thank you.

Kind Regards,
Mihail Velikov

**Comment by shettyg** [comment]
>Btw I noticed an interesting thing. Lets say that my linux gateway machine has the overlay running on 192.168.1.5 IP address and my nodeport should be listening on port 30080. If I try to connect to this IP from another host with telnet - it works. When I ssh to this machine and try to connect to the same address it does not work. It seems like it is missing a hairpin NAT and I believe this is the same reason the port forwarding also does not work.

That is right. There is an assumption that ingress happens from outside the machine and a openflow rule added that says that any traffic coming from "eth0" (physical interface) with a particular tcp port (nodeport) go to OVN and everything else go to local stack.

If you do 'ovs-ofctl dump-flows $physical_bridge' you will see the rules that do this.

**Comment by shettyg** [comment]
We have a k8s-$NODENAME interface with a IP address. I was thinking that, if kube-proxy iptables can convert nodeport to a pod IP address and we have some iptables rule to change the src IP address to the k8s-$NODENAME, then things should work.

**Comment by shettyg** [comment]
>Well, the best case scenario is to be able to select on which interface a nodeport should be exposed. For example our ingress should be on the EXT but microservices should be on the INT network.

Do you need nodeport on INT network? Or do you only need it on EXT network?

**Comment by shettyg** [comment]
Let me spend some time to see what needs to be done to expose nodeport both on EXT and INT on the same host.

**Comment by shettyg** [comment]
I think this should solve the issue for you. Let me know if it works.
https://github.com/openvswitch/ovn-kubernetes/pull/389

Effectively, you need to run whatever you are running on the node right now with ovnkube. In addition, for the extra interface, you should run something like:

```
sudo ovnkube   -nb-address=ssl://192.168.33.11:6641 -sb-address=ssl://192.168.33.11:6642  -k8s-kubeconfig /home/vagrant/kubeconfig.yaml -loglevel=4 -logfile=/var/log/openvswitch/ovnkube1.log -k8s-apiserver=http://192.168.33.11:8080 -init-gateways -gateway-interface=enp0s9 -gateway-nexthop=10.10.0.1 -gateway-name=k8sminion1 -nodeport -nb-client-privkey /etc/openvswitch/ovncontroller-privkey.pem -nb-client-cert /etc/openvswitch/ovncontroller-cert.pem -nb-client-cacert /etc/openvswitch/ovnnb-ca.cert -sb-client-privkey /etc/openvswitch/ovncontroller-privkey.pem -sb-client-cert /etc/openvswitch/ovncontroller-cert.pem -sb-client-cacert /etc/openvswitch/ovnsb-ca.cert -cluster-subnet=192.168.0.0/16
```

Important ones above are:
```
 -init-gateways -gateway-interface=enp0s9 -gateway-nexthop=10.10.0.1 -gateway-name=k8sminion1 -nodeport
```

I don't have a machine with extra interfaces, but it does work on a single interface.

**Comment by mihail-velikov** [comment]
@shettyg 

Thanks for the help! I will try to deploy now and see how it goes.

**Comment by mihail-velikov** [comment]
@shettyg 

I have redeployed our cluster and at first glance it seems to work. I am able to connect to the EXT interface and get redirected to the nginx ingress default backend.

Unfortunately I am hitting an issue where the containers do not have connectivity outside of the cluster. This might be related to the fact that the default gateway (and the machines connectivity to the internet) is done though the INT interface. So for example if I do:
ping -I INT 8.8.4.4 - > it works
ping -I EXT 8.8.4.4 - > no traffic

I tried to add --gateway-nexthop parameter to the secondary ovnkube command to point to the machines default gateway (pretty much how it works out of the box) but it didn't seem to help.

Do I need to add this parameter to both ovnkube commands? Previously I did not set this parameter at all due to the fact that by default it uses the default gateway listed in 'route -n'

Thank you.

Kind Regards,
Mihail Velikov

**Comment by shettyg** [comment]
@mihail-velikov 

I see what you mean. The patch needs an enhancement. Let me work on it.

**Comment by shettyg** [comment]
So we need to be able to pass a new subnet (via  new option) for a gateway which will tell us what is reachable via it. Would that work for you? For e.g., EXT gateway will have a new option called --subnet-via-gateway="0.0.0.0/0" and INT gateway will have "--subent-via-this-gateway="10.1.1.0/24,192.168.1.0/24" etc.

**Comment by mihail-velikov** [comment]
@shettyg - I think this will be fine, I don't mind adding another parameter to the ovnkube as it should be simple enough. 

Btw - one thing I do not yet understand is how the traffic routed from the container to the internet. I can see that each subnet has a default gateway IP but from there I am not able to see how the decision is made though which NAT node the traffic will go through. I checked the routing rules in the openvswitch routing devices but it was not clear for me.

Thanks a lot!

Mihail Velikov

**Comment by mihail-velikov** [comment]
@shettyg  - Disregard this for now please. After some internal talks it seems that it would be better for us to use a simple tcp load balancer that will sit outside of our kubernetes solution.

**Comment by mihail-velikov** [comment]
Hello all,

Please feel free to close this issue. We moved to using nginx loadbalancing in front of our cluster and it seems to work pretty well.

Thank you for the help.

Kind Regards,
Mihail Velikov
