### ISSUE TITLE
Can not find 'ovn-k8s-overlay' file when building the ovn-kube image

### ISSUE THREAD

**Issue by zhaozhanqi** [openvswitch/ovn-kubernetes#381]
hi
 I'm trying rebuild the ovn-kube image in ovn-kubernetes/dist/images, there is one step in the Dockerfile 
```
Step 10/15 : COPY ovn-k8s-overlay ovnkube ovn-kube-util /usr/bin/
lstat ovn-k8s-overlay: no such file or directory
```
I already built the related in ovn-kubernetes/go-controller
```
# make install
install -D -m 755 _output/go/bin/ovnkube /usr/bin/
install -D -m 755 _output/go/bin/ovn-kube-util /usr/bin/
install -D -m 755 _output/go/bin/ovn-k8s-cni-overlay -t /opt/cni/bin/
```
Seems there is NO this file `ovn-k8s-overlay`, is this file still need?
thanks

**Comment by pecameron** [comment]
This is fixed. 
cd ovn-kuberntes
docker build -t ovn-kube -f Dockerfile.centos .

**Comment by zhaozhanqi** [comment]
thanks @pecameron
