### ISSUE TITLE
ovnkube initialization : kubeconfig.yaml missing

### ISSUE THREAD

**Issue by jrish1** [openvswitch/ovn-kubernetes#383]
I am new to Kubernetes and trying to set OVN as the CNI for it. In the documentation to initialize ovnkube on Master, the execution steps have an kubeconfig.yaml file.

Is this file or a template provided in any documentation? If not, is it supposed to contain the desired OVS configuration ?

Thanks for the help

**Comment by shettyg** [comment]
@jrish1 

kubeconfig.yaml is a file which contains information on how to connect to the kube-apiserver for a client. You may want to checkout out the vagrant directory in the repo if your goal is to get up a simple kubernetes cluster with OVN. If your goal is to know individual steps on how to install, then for a single node k8s setup, you can see the following 2 scripts:

https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-master.sh

https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-k8s-master.sh
