### ISSUE TITLE
Cannot access internet from containers when launched through kubernetes

### ISSUE THREAD

**Issue by cn-mayank** [openvswitch/ovn-kubernetes#404]
I have installed kubernetes via the ansible playbook in contrib. 
When i launch a pod whether on linux node or windows node, they are not able to access the internet.
However when i use the same docker image and launch a container manually(via docker) from the same ec2-instances, they are able to access internet.

I have launched 2 linux ec2 instances for master and linux-minion and 1 windows instance for windows minion within a vpc.

**Comment by shettyg** [comment]
@aserdean 

Does the ansible scripts create a gateway?

**Comment by cn-mayank** [comment]
So i checked the output and I must have missed this among output of many tasks, but i am getting following output in the ansible script run: 

TASK [windows/kubernetes : Kubernetes | Check ping to OVN gateway] **********************************************************************************
fatal: [10.224.138.119]: FAILED! => {"changed": false, "cmd": "ping 10.0.1.1 -n 1", "delta": "0:00:04.467175", "end": "2018-07-27 04:48:29.202509", "msg": "non-zero return code", "rc": 1, "start": "2018-07-27 04:48:24.735333", "stderr": "", "stderr_lines": [], "stdout": "\r\nPinging 10.0.1.1 with 32 bytes of data:\r\nRequest timed out.\r\n\r\nPing statistics for 10.0.1.1:\r\n    Packets: Sent = 1, Received = 0, Lost = 1 (100% loss),\r\n", "stdout_lines": ["", "Pinging 10.0.1.1 with 32 bytes of data:", "Request timed out.", "", "Ping statistics for 10.0.1.1:", "    Packets: Sent = 1, Received = 0, Lost = 1 (100% loss),"]}
...ignoring

**Comment by alinbalutoiu** [comment]
@shettyg the ansible scripts should create the gateway on the first linux minion node.

@cn-mayank that is not an error, it's just a check on the Windows side to see if ovnkube minion-init has been ran before. Can you send the output of ``ovs-vsctl show`` on the linux minion node?

**Comment by cn-mayank** [comment]
Thanks for clarifying about the ping-task. 

Here is the output of the ovs-vsctl show command from linux-minion:
`a5494e5d-5a02-454b-b892-4b2605d0a11c
    Bridge br-int
        fail_mode: secure
        Port "k8s-ip-10-224-1"
            Interface "k8s-ip-10-224-1"
                type: internal
        Port "ovn-649a29-0"
            Interface "ovn-649a29-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="10.224.138.37"}
        Port "ovn-6c6e0d-0"
            Interface "ovn-6c6e0d-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="10.224.139.37"}
        Port "k8s-patch-br-int-breth0"
            Interface "k8s-patch-br-int-breth0"
                type: patch
                options: {peer="k8s-patch-breth0-br-int"}
        Port br-int
            Interface br-int
                type: internal
    Bridge "breth0"
        fail_mode: standalone
        Port "eth0"
            Interface "eth0"
        Port "k8s-patch-breth0-br-int"
            Interface "k8s-patch-breth0-br-int"
                type: patch
                options: {peer="k8s-patch-br-int-breth0"}
        Port "breth0"
            Interface "breth0"
                type: internal
    ovs_version: "2.9.2"`

**Comment by alinbalutoiu** [comment]
@cn-mayank Thanks for the update.
Just to make sure, the pods from Windows are able to access internal IPs from within the cluster (such as other pod IPs or service IPs) but not able to access the internet?
Can you check if on the linux minion the ``ovnkube-gateway-helper`` service is running?

**Comment by cn-mayank** [comment]
To verify pods from Windows are able to access internal IPs, I launched two deployments which correspondingly got ip 10.0.1.3 and 10.0.1.4. Both pods were able to ping each other at the above ips.

On linux minion, i could not find **ovnkube-gateway-helper** in output of service --status-all, neither i could find a process running with that name

**Comment by alinbalutoiu** [comment]
Can you check if you have this file created on the linux minion? ``/etc/systemd/system/ovnkube-gateway-helper.service``
Did you set by any chance this on false before running the playbook? https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/ovn-kubernetes-cluster.yml#L29

**Comment by cn-mayank** [comment]
the `init_gateway` parameter is set to true in ovn-kubernetes-cluster.yml

The file `/etc/systemd/system/ovnkube-gateway-helper.service` exists in linux minion and has following content
`
root@ip-10-224-137-1:~# cat /etc/systemd/system/ovnkube-gateway-helper.service
# BEGIN ANSIBLE MANAGED BLOCK
[Unit]
Description=OVN Gateway Helper
Documentation=https://github.com/openvswitch/ovn-kubernetes
[Service]
ExecStart=/usr/bin/ovnkube \
  -init-node "ip-10-224-137-1" \
  -cluster-subnet "10.0.0.0/16" \
  -k8s-token 
xxxxlongstrxxx \
  -k8s-cacert /etc/openvswitch/k8s-ca.crt \
  -k8s-apiserver "http://10.224.140.199:8080" \
  -service-cluster-ip-range "10.1.0.0/24" \
  -nodeport \
  -init-gateways \
  -gateway-interface=eth0 \
  -gateway-nexthop="10.224.128.1" \
  -nb-address tcp://10.224.140.199:6641 \
  -sb-address tcp://10.224.140.199:6642
Restart=on-failure
RestartSec=10
WorkingDirectory=/root/
[Install]
WantedBy=multi-user.target
# END ANSIBLE MANAGED BLOCK
`

**Comment by alinbalutoiu** [comment]
Can you start the service with ``systemctl start ovnkube-gateway-helper`` and check if you get any errors?

**Comment by cn-mayank** [comment]
So the command i used to check if ovn-gateway-helper was up `service --status-all` was not right. Using `systemctl` i could see that ovn-gateway-helper was up.
`
ovnkube-gateway-helper.service                               loaded active running   OVN Gateway Helper
`

Next i found that actual issue is in dns resolving. When i directly ping ip address of any website (say kubernetes.io) it was successful but trying to ping kunbernetes.io fails. 

This [link](https://gist.github.com/cn-mayank/1b876b94d93482452e20460b240d54bf) shows the ipconfig on the windows minion. As you can see, the etheret adapter k8s-ec2amaz-cvb does not have proper dns entries. I tried to add dns-server entry manually but not successful yet.

 what can be done so that appropriate dns entries get created as part of playbook itself ? Appreciate the help @alinbalutoiu and others.

**Comment by aserdean** [comment]
Please make sure that you have DNS servers passed inside the CNI config on Windows (i.e.: https://github.com/openvswitch/ovn-kubernetes/pull/346#issuecomment-392753235). Unfortunately it is still a nuisance on Windows.

At the moment you can use the commandlets: 
https://docs.microsoft.com/en-us/powershell/module/dnsclient/set-dnsclientserveraddress?view=win10-ps 

Just to make sure: can you ping a website from the host? Or you can't just from the containers?

**Comment by cn-mayank** [comment]
I can ping all websites from host, the issue occurs only when i ping from within the container.

When i edited the cni config file with dns servers, the containers were able to access internet. Thanks for sharing the PR link. I hope I did not miss this instruction from some readme. 

However there is still an dns issue i found, does master-node also require some config file edit ?
`
root@ip-10-224-128-133:~# kubectl logs webserver-6669578645-zzrxg
Error from server: Get https://ec2amaz-skepkg0:10250/containerLogs/default/webserver-6669578645-zzrxg/webserver: dial tcp: lookup ec2amaz-skepkg0 on 10.224.0.2:53: no such host
`

**Comment by aserdean** [comment]
Yay! I'll try to 

You shouldn't. On Linux the pods should get the nameservers and search domain from the host configuration file (`/etc/resolv.conf`)

**Comment by cn-mayank** [comment]
Following is the content of /etc/resolv.conf on master and linux-minion
`
domain factory.local
search factory.local
nameserver 10.212.70.10
nameserver 10.212.71.10
nameserver 10.224.0.2
nameserver 8.8.8.8
`

I have another cluster of linux only nodes which was brought up via kops and calico. On those nodes, the /etc/resolv.conf file is as follows:
`
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.212.70.10
nameserver 10.212.71.10
nameserver 10.224.0.2
search factory.local
`
As you can see they are identical inspite of being separate clusters and are in the same vpc and the same subnet. On the second kops managed cluster, i am able to perform kubectl logs and kubectl exec. On the ovn cluster, i am not able to do logs/exec be it for windows or linux minion pods.

When we look at the message `Error from server: Get https://ip-10-224-130-234:10250/containerLogs/default/webserver2-6f84664d79-brqzg/webserver2: dial tcp: lookup ip-10-224-130-234 on 10.224.0.2:53: no such host` , we can see that it queried the right host `10.224.0.2:53` . Thus my hunch is that some kind of registration step/config or maybe discoverability is missing. Any ides ?

**Comment by cn-mayank** [comment]
Hey @aserdean @alinbalutoiu ,
any thoughts on not being able to exec in pods on windows/linux minions ? `Error from server: Get https://ip-10-224-130-234:10250/containerLogs/default/webserver2-6f84664d79-brqzg/webserver2: dial tcp: lookup ip-10-224-130-234 on 10.224.0.2:53: no such host`

Would you rather recommend to raise a different issue for it ? Thanks!

**Comment by cn-mayank** [comment]
I followed steps referred in #410 and was able to access the internet from containers. But since last few days, when i create a cluster via ansible playbook in contrib, the containers are not able to access internet. 
I found below indicators in logs on linux minion if they point to any issue:
`ovn-nbctl list logical_router
ovn-nbctl: unix:/var/run/openvswitch/ovnnb_db.sock: database connection failed (No such file or directory)`

`● openvswitch-switch.service - LSB: Open vSwitch switch
   Loaded: loaded (/etc/init.d/openvswitch-switch; bad; vendor preset: enabled)
   Active: active (running) since Wed 2018-09-26 13:46:32 UTC; 10min ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 7
   Memory: 28.4M
      CPU: 697ms
   CGroup: /system.slice/openvswitch-switch.service
           ├─31537 ovsdb-server: monitoring pid 31538 (healthy)                                                                                                                      
           ├─31538 ovsdb-server /etc/openvswitch/conf.db -vconsole:emer -vsyslog:err -vfile:info --remote=punix:/var/run/openvswitch/db.sock --private-key=db:Open_vSwitch,SSL,privat
           ├─31547 ovs-vswitchd: monitoring pid 31548 (healthy)                                                                                                                      
           └─31548 ovs-vswitchd unix:/var/run/openvswitch/db.sock -vconsole:emer -vsyslog:err -vfile:info --mlockall --no-chdir --log-file=/var/log/openvswitch/ovs-vswitchd.log --pi

Sep 26 13:46:32 ip-10-224-129-219 ovs-vsctl[31539]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --no-wait -- init -- set Open_vSwitch . db-version=7.15.1
Sep 26 13:46:32 ip-10-224-129-219 ovs-vsctl[31544]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --no-wait set Open_vSwitch . ovs-version=2.9.2 "external-ids:system-id=\"e6c0ebef-40d7-4
Sep 26 13:46:32 ip-10-224-129-219 openvswitch-switch[31494]:  * Configuring Open vSwitch system IDs
Sep 26 13:46:32 ip-10-224-129-219 openvswitch-switch[31494]:  * Starting ovs-vswitchd
Sep 26 13:46:32 ip-10-224-129-219 openvswitch-switch[31494]: hostname: Name or service not known
Sep 26 13:46:32 ip-10-224-129-219 openvswitch-switch[31494]:  * Enabling remote OVSDB managers
Sep 26 13:46:32 ip-10-224-129-219 ovs-vsctl[31557]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --no-wait set Open_vSwitch . external-ids:hostname=
Sep 26 13:46:32 ip-10-224-129-219 ovs-vsctl[31557]: **ovs|00002|db_ctl_base|ERR|external-ids:hostname=: argument does not end in "=" followed by a value.**
Sep 26 13:46:32 ip-10-224-129-219 openvswitch-switch[31494]: **ovs-vsctl: external-ids:hostname=: argument does not end in "=" followed by a value.**
Sep 26 13:46:32 ip-10-224-129-219 systemd[1]: Started LSB: Open vSwitch switch.
`

Is this expected ? Would really appreciate any pointers. Thanks!

**Comment by cn-mayank** [comment]
`ovs-vsctl get open_vswitch . external_ids
{"k8s-api-server"="http://10.224.129.219:8080", "k8s-api-token"="eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tNXhscW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImQ4Nzg1NGRiLWMxOTEtMTFlOC04ZDFlLTEyM2U3ZDU2NzU4NiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.n4r6vcRYpV4hEbnrRaSqkSRTZ_r589-Cr6crKN1SsFYNVL_0xVJahRCb9FXLXvnt9-oLheKeOvHNGk2S-nKspbZrolIhhrRtWJpRdO9Zwnj9hDhnOX_eS-y7xR5wRVBJ6uSLdWcfcEw06q6rYyTBn_ZLY4_qVC25R7MxII2ZqfS7AW3uPPc591I6gYTBw2WLm41zTB7OteFatI9WKI_59_L8p5uKFOQKeZWwRmgczgzXSY_m8fN6NDOkp_tCBuuREFOpPCW82dj1lMNeRkuLjKd_k34NSoH1fEflqT4JRekcqiThrlls9G0LfGujJ1oGU-DPdN7oq8KYi98tnlXAgQ", ovn-encap-ip="10.224.129.219", ovn-encap-type=geneve, ovn-nb="tcp:10.224.129.149:6641", ovn-remote="tcp:10.224.129.149:6642", rundir="/var/run/openvswitch", system-id="e6c0ebef-40d7-4b82-8ba9-52dc3a027e15"}
`

**Comment by cn-mayank** [comment]
I will close the issue here as below response solved the original problem. And although the current problem I am facing has same effect, but cause is missing hostname in external_ids row which perhaps can be separate issue

> Hi @cn-mayank , I think that the issue you are hitting now it's the same as #410
> Let's continue there.
