### ISSUE TITLE
kubectl stops when restarting VM 

### ISSUE THREAD

**Issue by alissonpmedeiros** [openvswitch/ovn-kubernetes#407]
Hi everyone,

I'm trying to use ovn-kubernetes via **vagrant** in ubuntu 18 and following this tutorial: https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/README.md

Everything goes fine, from installation to pod creation but when I restart the VM and try to use **kubectl** I got: `The connection to the server localhost:8080 was refused - did you specify the right host or port?` 

can anybody help me? after restarting the VM do I need to start some service?

**Comment by shettyg** [comment]
@alissonpmedeiros 

The vagrant is not designed to handle restarts. It is just for someone to get familiar with OVN installation procedure. It starts kubernetes daemons without the help of startup scripts. i.e., it does:

https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-master.sh#L138
 So after a restart, one will have to re-run those scripts.

**Comment by alissonpmedeiros** [comment]
Hi @shettyg , thanks for your help.
I realized that in **master** and **minion** I need to restart some services and I created a script to restart these services after restarting a VM.

The activation of the docker container (google container) must be done manually in the master, that is, through the container ID, which must be placed in the script. Additionally, the IPs on the master and the minion should be placed in the script as well. I hope you can help someone else.


**initialize_master_services.sh**
`#!/bin/bash

# public ip from master node(k8s-master) defined in vm_config.conf.yml
MASTER1=10.10.0.11
PROTOCOL="ssl"
OVERLAY_IP=$MASTER1

echo "starting google containers..."
sudo docker container start 6f5334bce31f


sudo sh -c 'echo "PATH=$PATH:$HOME/k8s/server/kubernetes/server/bin" >> /etc/profile'
pushd k8s/server/kubernetes/server/bin
echo "Starting kube-apiserver ..."

nohup sudo ./kube-apiserver --service-cluster-ip-range=172.16.1.0/24 \
                            --address=0.0.0.0 \
                            --etcd-servers=http://127.0.0.1:4001 \
                            --advertise-address=$MASTER1 \
                            --v=2 2>&1 0<&- &>/dev/null &

# Wait till kube-apiserver starts up
while true; do
    ./kubectl get nodes
    if [ $? -eq 0 ]; then
        break
    fi
    echo "waiting for kube-apiserver to start...."
    sleep 1
done

echo "Starting kube-controller-manager ..."
nohup sudo ./kube-controller-manager --master=127.0.0.1:8080 --v=2 2>&1 0<&- &>/dev/null &

echo "Starting kube-scheduler ..."
nohup sudo ./kube-scheduler --master=127.0.0.1:8080 --v=2 2>&1 0<&- &>/dev/null &

popd

cat << KUBECONFIG >> ~/kubeconfig.yaml
apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8080
  name: default-cluster
- cluster:
    server: http://localhost:8080
  name: local-server
- cluster:
    server: http://localhost:8080
  name: ubuntu
contexts:
- context:
    cluster: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: p1NVMZqhOOOqkWQq
    username: admin
KUBECONFIG

pushd k8s/server/kubernetes/server/bin
nohup sudo ./kubelet --kubeconfig $HOME/kubeconfig.yaml \
                     --v=2 --address=0.0.0.0 \
                     --fail-swap-on=false \
                     --runtime-cgroups=/systemd/system.slice \
                     --kubelet-cgroups=/systemd/system.slice \
                     --enable-server=true --network-plugin=cni \
                     --cni-conf-dir=/etc/cni/net.d \
                     --cni-bin-dir="/opt/cni/bin/" >/tmp/kubelet.log 2>&1 0<&- &
popd

if [ $PROTOCOL = "ssl" ]; then
 SSL_ARGS="-nb-server-privkey /etc/openvswitch/ovnnb-privkey.pem \
 -nb-server-cert /etc/openvswitch/ovnnb-cert.pem \
 -nb-server-cacert /vagrant/pki/switchca/cacert.pem \
 -sb-server-privkey /etc/openvswitch/ovnsb-privkey.pem \
 -sb-server-cert /etc/openvswitch/ovnsb-cert.pem \
 -sb-server-cacert /vagrant/pki/switchca/cacert.pem  \
 -nb-client-privkey /etc/openvswitch/ovncontroller-privkey.pem \
 -nb-client-cert /etc/openvswitch/ovncontroller-cert.pem \
 -nb-client-cacert /etc/openvswitch/ovnnb-ca.cert \
 -sb-client-privkey /etc/openvswitch/ovncontroller-privkey.pem \
 -sb-client-cert /etc/openvswitch/ovncontroller-cert.pem \
 -sb-client-cacert /etc/openvswitch/ovnsb-ca.cert"
fi


ovn_nb="$PROTOCOL://$OVERLAY_IP:6641"
ovn_sb="$PROTOCOL://$OVERLAY_IP:6642"

nohup sudo ovnkube -k8s-kubeconfig $HOME/kubeconfig.yaml -net-controller -loglevel=4 \
 -k8s-apiserver="http://$OVERLAY_IP:8080" \
 -logfile="/var/log/openvswitch/ovnkube.log" \
 -init-master="k8smaster" -cluster-subnet="192.168.0.0/16" \
 -init-node="k8smaster" \
 -service-cluster-ip-range=172.16.1.0/24 \
 -nodeport \
 -k8s-token="test" \
 -nb-address="$ovn_nb" \
 -sb-address="$ovn_sb" \
 -init-gateways -gateway-localnet \
 ${SSL_ARGS} 2>&1 &>/dev/null &

echo "END SCRIPT!"`

**initialize_node_services.sh**
`#!/bin/bash

PROTOCOL="ssl"
MASTER1=10.10.0.12
GW_IP=10.10.0.1

# Install certificates
pushd /etc/openvswitch
sudo ovs-pki req ovncontroller
sudo ovs-pki -b -d /vagrant/pki sign ovncontroller switch
popd

# Start k8s daemons
pushd k8s/server/kubernetes/server/bin
echo "Starting kubelet ..."
nohup sudo ./kubelet --kubeconfig $HOME/kubeconfig.yaml \
                     --v=2 --address=0.0.0.0 \
                     --fail-swap-on=false \
                     --runtime-cgroups=/systemd/system.slice \
                     --kubelet-cgroups=/systemd/system.slice \
                     --enable-server=true --network-plugin=cni \
                     --cni-conf-dir=/etc/cni/net.d \
                     --cni-bin-dir="/opt/cni/bin/" >/tmp/kubelet.log 2>&1 0<&- &
popd

# Initialize the minion and gateway.
if [ $PROTOCOL = "ssl" ]; then
  SSL_ARGS="-nb-client-privkey /etc/openvswitch/ovncontroller-privkey.pem \
    -nb-client-cert /etc/openvswitch/ovncontroller-cert.pem \
    -nb-client-cacert /etc/openvswitch/ovnnb-ca.cert \
    -sb-client-privkey /etc/openvswitch/ovncontroller-privkey.pem \
    -sb-client-cert /etc/openvswitch/ovncontroller-cert.pem \
    -sb-client-cacert /etc/openvswitch/ovnsb-ca.cert"
fi

ovn_nb="$PROTOCOL://$MASTER1:6641"
ovn_sb="$PROTOCOL://$MASTER1:6642"

nohup sudo ovnkube -k8s-kubeconfig $HOME/kubeconfig.yaml -loglevel=4 \
    -logfile="/var/log/openvswitch/ovnkube.log" \
    -k8s-apiserver="http://$MASTER1:8080" \
    -init-node="$MINION_NAME"  \
    -nodeport \
    -nb-address="$ovn_nb" \
    -sb-address="$ovn_sb" \
    ${SSL_ARGS} \
    -k8s-token="test" \
    -init-gateways -gateway-interface=enp0s8 -gateway-nexthop="$GW_IP" \
    -service-cluster-ip-range=172.16.1.0/24 \
    -cluster-subnet="192.168.0.0/16" 2>&1 &>/dev/null &

sleep 10

echo "END SCRIPT"`

**Comment by alissonpmedeiros** [comment]
I think we can close this issue, since the problem was solved and the scripts to restart the services in master and minion are available.
