### ISSUE TITLE
Ansible and DNS

### ISSUE THREAD

**Issue by mkomu** [openvswitch/ovn-kubernetes#410]
Hi,

I have been testing ovn-kubernetes using the ansible playbook since I did not understand how the default installation instructions work. I am working using two OpenStack VMs, one master and one slave:

contrib/inventory/hosts:
  [kube-master]
  10.0.0.12 # real ip

  [kube-minions-linux]
  10.0.0.6 # real ip

I got the ansible installation to a state where I can launch containers but DNS is dysfunctional. Even running simple kubectl things on the master would trigger errors until I changed the following:

contrib/roles/linux/kubernetes/tasks/prepare_master.yml:
        --insecure-bind-address={{ host_public_ip }} \
        --insecure-bind-address=0.0.0.0 \

Now cubectl works, but DNS does not work inside the containers. It seems that dns module is not running in the master (or it is started via systemd somehow?):

ubuntu@cube-master-a-001:~$ kubectl get pods --all-namespaces
NAMESPACE   NAME      READY     STATUS    RESTARTS   AGE
default     alpine1   1/1       Running   0          57m

The cluster virtual ip configuration is as follows:

contrib/inventory/group_vars/all:
  CLUSTER_SUBNET: "192.168.0.0/16"
  MASTER_INTERNAL_IP: "192.168.0.2" # Should always be the second IP of CLUSTER_SUBNET
 
  SERVICE_CLUSTER_IP_RANGE: "192.168.1.0/24"
  K8S_DNS_DOMAIN: "cluster.local"
  K8S_DNS_SERVICE_IP: "192.168.9.10"
  K8S_API_SERVICE_IP: "192.168.9.1"

Can you give me some debugging hints?

**Comment by rajatchopra** [comment]
Can you check on the master if the DNS is being served at all? 
```
netstat -tulpn 
```

 1. Check for ports 53/8053
 2. See if you can resolve DNS from the master host itself: nslookup <svc-name>.<namespace>.svc.cluster.local 
 3. Can you resolve the DNS from minion?
 4. Check /etc/resolv.conf of the hosts and the pods

We would either make all pods use the host's IP address as the nameserver. And then use dnsmasq on the host to search for cluster contents on master-api server. Or, we can directly use the service 172.30.0.1 as the nameserver (which is inefficient).

**Comment by mkomu** [comment]
No ports 53/8053 available. Maybe the network configuration is busted, which prevents kubeadm from bringing the DNS module up?

kubectl exec -it alpine1 -- /bin/bash
Error from server: error dialing backend: dial tcp: lookup cube-slave-b-001 on 8.8.8.8:53: no such host

**Comment by alinbalutoiu** [comment]
Hi @mkomu ,

Thanks for trying out the ansible playbook.
Could you give more details regarding:
> Even running simple kubectl things on the master would trigger errors until I changed the following:
Could you be a bit more specific on the error types?

The ansible playbook is not deploying the DNS module at the moment, may I know how did you use kubeadm to bring the DNS module up? Thanks!

**Comment by rajatchopra** [comment]
Wait, can we even reach an external address from the pods? e.g. ping/curl the api server's IP address from the pod. Sounds like we have the gateway setup that is busted.

**Comment by cn-mayank** [comment]
Hey @rajatchopra ,
It seems that this issue is related to another problem i am facing at [404 comment](https://github.com/openvswitch/ovn-kubernetes/issues/404#issuecomment-410356756). Basically I am not able to run kubectl exec/logs due to dns issues.

Let me know if I can provide some data to help resolve the issue. Note that I am able to ping api-server's ip address from a pod, but i have also applied [336 comment](https://github.com/openvswitch/ovn-kubernetes/pull/346#issuecomment-392753235)

**Comment by mkomu** [comment]
Hi,

On 08/15/2018 01:25 AM, Alin Balutoiu wrote:
> Hi @mkomu <https://github.com/mkomu> ,
> 
> Thanks for trying out the ansible playbook.
> Could you give more details regarding:
> 
>     Even running simple kubectl things on the master would trigger
>     errors until I changed the following:
>     Could you be a bit more specific on the error types?
> 
> The ansible playbook is not deploying the DNS module at the moment, may 
> I know how did you use kubeadm to bring the DNS module up? Thanks!

I didn't. How this is supposed to be done? I think the DNS module is 
essential in a working kubernetes set up.

I think my ansible set up is just busted because I don't have enough 
running services (due to network issues?):

# kubectl get all --all-namespaces -o=wide
NAMESPACE   NAME      READY     STATUS    RESTARTS   AGE       IP 
     NODE
default     alpine1   1/1       Running   0          3d 
192.168.0.3   cube-slave-b-001

NAMESPACE   NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S) 
   AGE       SELECTOR
default     kubernetes   ClusterIP   192.168.1.1   <none>        443/TCP 
   3d        <none>

I got a bit further using the manual set up instructions and most 
services are up and running (except for working DNS module):

NODE_NAME=$(hostname)
TOKEN=<xx>
CENTRAL_IP=10.0.0.13 # real address
CLUSTER_IP_SUBNET=192.168.0.0/16 # overlay prefix
SERVICE_IP_SUBNET=192.168.1.0/24 # overlay prefix
KUBECONFIG=/etc/kubernetes/admin.conf

nohup sudo ovnkube -k8s-kubeconfig $KUBECONFIG -net-controller \
  -loglevel=4 \
  -k8s-apiserver="http://$CENTRAL_IP:8080" \
  -logfile="/var/log/openvswitch/ovnkube.log" \
  -init-master=$NODE_NAME -init-node=$NODE_NAME \
  -cluster-subnet="$CLUSTER_IP_SUBNET" \
  -service-cluster-ip-range=$SERVICE_IP_SUBNET \
  -nodeport \
  -k8s-token="$TOKEN" \
  -nb-address="tcp://$CENTRAL_IP:6641" \
  -sb-address="tcp://$CENTRAL_IP:6642" 2>&1 &

However, the only way here to make the set up to work is to use a 
*non-overlay* address as the k8s-apiserver and nb/sb-address. Is this 
intended?

However, the manual instructions still produce a malfunctional DNS module:

# kubectl describe -n kube-system pod/coredns-78fcdf6894-b5k4g
  Warning  FailedCreatePodSandBox  36m                 kubelet, 
cube-master-a-001  Failed create pod sandbox: rpc error: code = Unknown 
desc = failed to set up sandbox container 
"717d7c9346896dfabcd149cf7d6d80801bfc4ca7d30d845c640c1602567ac78e" 
network for pod "coredns-78fcdf6894-b5k4g": NetworkPlugin cni failed to 
set up pod "coredns-78fcdf6894-b5k4g_kube-system" network: failed to 
send CNI request: Post http://dummy/: dial unix 
/var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file 
or directory
   Warning  FailedCreatePodSandBox  36m                 kubelet, 
cube-master-a-001  Failed create pod sandbox: rpc error: code = Unknown 
desc = failed to set up sandbox container 
"86769e32ccc6d589be07d7773ab5c99b1b688e6ba95f48bdff23b89323155b8b" 
network for pod "coredns-78fcdf6894-b5k4g": NetworkPlugin cni failed to 
set up pod "coredns-78fcdf6894-b5k4g_kube-system" network: failed to 
send CNI request: Post http://dummy/: dial unix 
/var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file 
or directory

P.S. I can open a separate issue about the manual instructions if needed.

**Comment by mkomu** [comment]
Hi,

On 08/15/2018 03:02 AM, Rajat Chopra wrote:
> Wait, can we even reach an external address from the pods? e.g. 
> ping/curl the api server's IP address from the pod. Sounds like we have 
> the gateway setup that is busted.

in the ansible set up, I can't get a shell to the container because DNS 
fails:

kubectl exec -it alpine1 -- /bin/bash
Error from server: error dialing backend: dial tcp: lookup 
cube-slave-b-001 on 8.8.8.8:53: no such host

**Comment by alinbalutoiu** [comment]
Hi @mkomu ! I am a bit confused about your answer, I still couldn't understand the reason for when you said this:
> Even running simple kubectl things on the master would trigger errors until I changed the following:

Simple kubectl commands should be working if you deploy with the ansible playbook.

kubectl commands seem to be working fine:
```
root@k8s-minion-lin:/home/ubuntu# kubectl get pods
NAME         READY     STATUS    RESTARTS   AGE
alpine       1/1       Running   1          2d
apachetwin   1/1       Running   1          2d
nginxtwin    1/1       Running   1          2d
```

Unfortunately the manual instructions are not showing how to set up Kubernetes DNS.

However, if you want to run commands inside the pods without Kubernetes DNS, you'll have to go manually on the node where the pod is running, find the container that you want, and use ``docker exec`` to run commands. Example:
```
root@k8s-minion-lin:~# docker ps | grep alpine
f40279bb51dd        alpine                       "sleep 3600"             4 minutes ago       Up 4 minutes                            k8s_alpinedebug_alpine_default_8714149f-a013-11e8-b714-000c29c48b4b_1
0dbb1ad40292        k8s.gcr.io/pause-amd64:3.1   "/pause"                 4 minutes ago       Up 4 minutes                            k8s_POD_alpine_default_8714149f-a013-11e8-b714-000c29c48b4b_1
root@k8s-minion-lin:~# docker exec -it f40279bb51dd /bin/sh
/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=126 time=21.041 ms
64 bytes from 8.8.8.8: seq=1 ttl=126 time=21.375 ms
64 bytes from 8.8.8.8: seq=2 ttl=126 time=19.665 ms
64 bytes from 8.8.8.8: seq=3 ttl=126 time=19.095 ms
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 19.095/20.294/21.375 ms
/ #
```

**Comment by alinbalutoiu** [comment]
Hi @mkomu , for the ``kubectl exec`` commands to work it seems that it's enough to add minion hostnames in ``/etc/hosts``. I've sent an update to the playbooks which should do this automatically for you.
The cluster DNS will still not work inside the pods, working on a fix for that.

**Comment by shettyg** [comment]
@alinbalutoiu 

For the Ansible, it may make sense to run master with -gateway-localnet. This will get DNS pod started.  The nodeport should come from the first linux node.
