### ISSUE TITLE
Nodeport is not accessible on windows node

### ISSUE THREAD

**Issue by cn-mayank** [openvswitch/ovn-kubernetes#423]
**Note:** _Created a cluster via the ansible playbook of contrib_

I created a service of type NodePort for an exposed port.
For linux minion, hitting `node-ip:port` works perfectly.

For windows minion, if I reach from other pod (e.g. `curl 10.0.1.4:8113`) perfect response is returned.
However when simultaneously i try to reach from outside the cluster or from master node (curl `10.224.130.91:32130`), it says connection refused.

Suspecting it to be firewall issue, i added firewall rule also in the windows instance via
`netsh advfirewall firewall add rule name="expose nodeport" dir=in action=allow protocol=TCP localport=32130
netsh advfirewall firewall add rule name="expose nodeport" dir=out action=allow protocol=TCP localport=32130` but it remained connection refused. 

As per my knowledge, firewall inside the container should not be issue. **kube-proxy** is supposed to proxy the request to endpoint `10.0.1.4:8113` and the endpoint is working, it is responding as expected thus the firewall in container is not issue, just that the request never reaches pod

Using wireshark I could confirm that request packet is reaching the intended host but it immediately gets response of connection refused

**Comment by cn-mayank** [comment]
I tries again by adding `-nodeport` in the ovnkube options for windows minion at [here](https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/roles/windows/kubernetes/tasks/run_minion_init.yml#L45). But the result is still same and not able to access service via nodeport

**Comment by rajatchopra** [comment]
Assuming 10.0.1.4 is your windows node, the nodeport functionality is missing on Windows because there is no gateway setup for the Windows node. It is an untested code path yet.
Did you try creating a Windows gateway by the way? It is not expected to work, but I have been even afraid to try it :).

**Comment by cn-mayank** [comment]
Thanks @rajatchopra , my node ip is `10.224.130.91`. The ip `10.0.1.4` is the **pod-ip**. 

If you or someone can guide, I would like to test by setting up the gateway and try resolving any issue if i face
Regards.

**Comment by alinbalutoiu** [comment]
Hi @cn-mayank, this is not a supported scenario at the moment. We will let you know when the PR is up for testing.

**Comment by cn-mayank** [comment]
Ok, thanks @alinbalutoiu. Currently what is the recommended way to access a service from outside the cluster ?

**Comment by cn-mayank** [comment]
Can I use ingress L7 or external-ip method to reach a pod running on windows-minion also ?

For L7 method, my understanding is that I can point a url+path to certain entity, but I am not sure to what do I point it ?

External-ip looks really good and simple too, great if i can reach a windows-minion pod via that.
Apologies for asking directly without trying, would have tried it first if i could now.

**Comment by cn-mayank** [comment]
Hi @rajatchopra , I am not clear about:
> but you will have to reach it through the default gateway on the first Linux node
can you please explain further.

I tried  creating a service with external-ip, however i got connection refused for both types of pod i.e. pod running on windows/linux minion. How can we inspect entries on the default gateway ?

**Comment by rajatchopra** [comment]
The default gateway is a router. Check it with ovn-nbctl list logical_router.
There should also be a load balancer associated with it. Or you can search for all global load balancers 'ovn-nbctl find load_balancer'. In the load balancer associated with the gateway router, you should see the VIP entries showing the external_ip fanning out to pod IP addresses as matched by service endpoints.

**Comment by shettyg** [comment]
@cn-mayank 

1. A nodeport results in a IP:nodeport NAT entry in a OVN "gateway". This can be on any host. So in this case, you can have this on a linux node.  So in that case, it will be "linuxnodeIP:Nodeport" -> loadbalancer -> Pods. These pods can reside on any node - in your case a windows node.


2. externalIP is only if that externalIP can be routed to a node. i.e an external entity (e.g your physical router) can get the packet with that externalIP to your nodes.


3. A L7 ingress LB is kubernetes object independent of OVN. For e.g., nginx. This LB will convert the nodeIP:port to a k8s service IP. This k8s service IP can be load-balanced by OVN to pods - which is the same as how OVN gets kubernetes services to work.

**Comment by cn-mayank** [comment]
Sorry for the delayed response, I got stuck in other project. 
@shettyg @rajatchopra , i am able to access services by hitting "linuxnodeIP:Nodeport" as you suggested. Thanks for the tip!
