### ISSUE TITLE
Router deploy pod cannot be running since ovnkube did not be deploy on router node

### ISSUE THREAD

**Issue by zhaozhanqi** [openvswitch/ovn-kubernetes#428]
From the yaml/ovnkube.yaml, the ovnkube pod only work on the label node "'node-role.kubernetes.io/compute=true'. but for now the openshift router node do not have this label. 
so ovnkube pod did not be deploy on the router node.  and it causes the router deploy pod cannot be running with error
```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ecbb00d5149d8c7a240383f89c2be71bc5736d471bbadc61d9e3861b46b89e0c" network for pod "router-1-deploy": NetworkPlugin cni failed to set up pod "router-1-deploy_default" network: failed to send CNI request: Post http://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory
``` 

Can we delete the `node-role.kubernetes.io/compute=true` in the yaml/ovnkube.yaml?

**Comment by zhaozhanqi** [comment]
@pecameron  could you help check this issue.

**Comment by pecameron** [comment]
@zhaozhanqi I spoke with Weibin your setup does not correctly label the nodes. Just add the missing label on the problem node. This is a dev preview issue only. The tech preview runs the daemonsets differently.

**Comment by zhaozhanqi** [comment]
@pecameron  the router node is not this label `node-role.kubernetes.io/compute=true` by default using the openshift-ansible installation. So I don't think add label is perfect method since maybe customer do not want to schedule pod on router node. 
But anyway, https://github.com/openvswitch/ovn-kubernetes/pull/471 had been resolved this issue.

```
[root@ip-172-18-13-248 ~]# oc get node
NAME                            STATUS    ROLES     AGE       VERSION
ip-172-18-13-248.ec2.internal   Ready     master    33m       v1.11.0+d4cacc0
ip-172-18-15-242.ec2.internal   Ready     <none>    29m       v1.11.0+d4cacc0
ip-172-18-8-255.ec2.internal    Ready     compute   29m       v1.11.0+d4cacc0
[root@ip-172-18-13-248 ~]# oc get pod
NAME                   READY     STATUS    RESTARTS   AGE
ovnkube-bsntq          3/3       Running   0          7m
ovnkube-cctlz          3/3       Running   0          7m
ovnkube-master-wzvl8   2/2       Running   0          6m
ovnkube-n8wpg          3/3       Running   0          7m
```
