### ISSUE TITLE
ovnkube: Failed to get mac address

### ISSUE THREAD

**Issue by ZhangZhenhua** [openvswitch/ovn-kubernetes#429]
I am trying to play with ovn/k8s but ovnkube panics as the backtrace below:

```
panic: Failed create management port: Failed to get mac address of k8s-zhenhua-ovs

goroutine 1 [running]:
main.runOvnKube(0xc4203971e0, 0x0, 0x0)
        /home/zhangzh/gohome/src/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:213 +0x1625
main.main.func1(0xc4203971e0, 0xc4203971e0, 0xc4202178bf)
        /home/zhangzh/gohome/src/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:100 +0x2b
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x1033480, 0x1255538, 0xc4203971e0, 0xc420087da0, 0x0)
        /home/zhangzh/gohome/src/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc42045ee00, 0xc42003a0f0, 0xf, 0xf, 0x0, 0x0)
        /home/zhangzh/gohome/src/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x60c
main.main()
        /home/zhangzh/gohome/src/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:103 +0x976

```

The procedure should be pretty standard for a kubeadm-built k8s cluster. After finishing *kubeadm init*, i started following the README in this repo. And when launching ovnkube, it panics.

From the code, I saw it tried to run a ovs-vsctl command. And here is the output in my env.
```
[root@zhenhua-ovs-1 ~]# ovs-vsctl show
aabc712d-b6a0-4ed1-a083-2eda28643c92
    Bridge br-int
        fail_mode: secure
        Port br-int
            Interface br-int
                type: internal
        Port "k8s-zhenhua-ovs"
            Interface "k8s-zhenhua-ovs"
                type: internal
    ovs_version: "2.10.90"
[root@zhenhua-ovs-1 ~]# ovs-vsctl --if-exists get interface k8s-zhenhua-ovs mac_in_use
[]
```

BTW, both current master and tag 0.3 have this issue.

Any help would be appreciated.

Thanks,
Zhenhua

**Comment by shettyg** [comment]
What does the following say?

1. "ovs-vsctl list interface k8s-zhenhua-ovs" 
2. ps -ef | grep ovs
3. lsmod | grep openvswitch

**Comment by ZhangZhenhua** [comment]
Thanks for your quick response!

```
[root@zhenhua-ovs-1 ~]# ovs-vsctl list interface k8s-zhenhua-ovs
_uuid               : 297fad84-60d1-48a4-b031-4836726879e4
admin_state         : []
bfd                 : {}
bfd_status          : {}
cfm_fault           : []
cfm_fault_status    : []
cfm_flap_count      : []
cfm_health          : []
cfm_mpid            : []
cfm_remote_mpids    : []
cfm_remote_opstate  : []
duplex              : []
error               : []
external_ids        : {iface-id="k8s-zhenhua-ovs-1.novalocal"}
ifindex             : []
ingress_policing_burst: 0
ingress_policing_rate: 0
lacp_current        : []
link_resets         : []
link_speed          : []
link_state          : []
lldp                : {}
mac                 : []
mac_in_use          : []
mtu                 : []
mtu_request         : 1400
name                : "k8s-zhenhua-ovs"
ofport              : []
ofport_request      : []
options             : {}
other_config        : {}
statistics          : {}
status              : {}
type                : internal


[root@zhenhua-ovs-1 ~]# ps -ef | grep ovs
openvsw+  8445     1  0 9月07 ?       00:00:05 ovsdb-server /etc/openvswitch/conf.db -vconsole:emer -vsyslog:err -vfile:info --remote=punix:/var/run/openvswitch/db.sock --private-key=db:Open_vSwitch,SSL,private_key --certificate=db:Open_vSwitch,SSL,certificate --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert --user openvswitch:openvswitch --no-chdir --log-file=/var/log/openvswitch/ovsdb-server.log --pidfile=/var/run/openvswitch/ovsdb-server.pid --detach
openvsw+  8504     1  0 9月07 ?       00:00:00 ovs-vswitchd unix:/var/run/openvswitch/db.sock -vconsole:emer -vsyslog:err -vfile:info --mlockall --user openvswitch:openvswitch --no-chdir --log-file=/var/log/openvswitch/ovs-vswitchd.log --pidfile=/var/run/openvswitch/ovs-vswitchd.pid --detach
root     12316     1  0 9月07 ?       00:00:00 ovsdb-server: monitoring pid 12317 (healthy)
root     12317 12316  0 9月07 ?       00:00:06 ovsdb-server -vconsole:off -vfile:info --log-file=/var/log/openvswitch/ovsdb-server-nb.log --remote=punix:/var/run/openvswitch/ovnnb_db.sock --pidfile=/var/run/openvswitch/ovnnb_db.pid --unixctl=ovnnb_db.ctl --detach --monitor --remote=db:OVN_Northbound,NB_Global,connections --private-key=db:OVN_Northbound,SSL,private_key --certificate=db:OVN_Northbound,SSL,certificate --ca-cert=db:OVN_Northbound,SSL,ca_cert --ssl-protocols=db:OVN_Northbound,SSL,ssl_protocols --ssl-ciphers=db:OVN_Northbound,SSL,ssl_ciphers /etc/openvswitch/ovnnb_db.db
root     12324     1  0 9月07 ?       00:00:00 ovsdb-server: monitoring pid 12325 (healthy)
root     12325 12324  0 9月07 ?       00:00:10 ovsdb-server -vconsole:off -vfile:info --log-file=/var/log/openvswitch/ovsdb-server-sb.log --remote=punix:/var/run/openvswitch/ovnsb_db.sock --pidfile=/var/run/openvswitch/ovnsb_db.pid --unixctl=ovnsb_db.ctl --detach --monitor --remote=db:OVN_Southbound,SB_Global,connections --private-key=db:OVN_Southbound,SSL,private_key --certificate=db:OVN_Southbound,SSL,certificate --ca-cert=db:OVN_Southbound,SSL,ca_cert --ssl-protocols=db:OVN_Southbound,SSL,ssl_protocols --ssl-ciphers=db:OVN_Southbound,SSL,ssl_ciphers /etc/openvswitch/ovnsb_db.db
root     23240 20705  0 10:37 pts/1    00:00:00 grep --color=auto ovs

[root@zhenhua-ovs-1 ~]# lsmod | grep openvswitch
openvswitch           114842  0 
nf_nat_ipv6            14131  1 openvswitch
nf_defrag_ipv6         35104  2 openvswitch,nf_conntrack_ipv6
nf_nat_ipv4            14115  2 openvswitch,iptable_nat
nf_nat                 26787  5 openvswitch,nf_nat_ipv4,nf_nat_ipv6,xt_nat,nf_nat_masquerade_ipv4
nf_conntrack          133053  9 openvswitch,nf_nat,nf_nat_ipv4,nf_nat_ipv6,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4,nf_conntrack_ipv6
libcrc32c              12644  4 xfs,openvswitch,nf_nat,nf_conntrack

```

**Comment by shettyg** [comment]
There is a error in the sense that "k8s-zhenhua-ovs" does not have a ofport value - which is odd. Likely, you don't see anything with "ifconfig k8s-zhenhua-ovs"?

1. Can you paste the contents of /var/log/openvswitch/ovs-vswitchd.log? There must be some errors there.

2. Also, the o/p of: ovs-vsctl --version.

3. Also, what platform is this? i.e Ubuntu? Or RHEL/Centos?

**Comment by ZhangZhenhua** [comment]
This is on centos 7.4.

```
[root@zhenhua-ovs-1 ~]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[root@zhenhua-ovs-1 ~]# uname -a
Linux zhenhua-ovs-1.novalocal 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

And actually there is no k8s-zhenhua-ovs interface.
```
[root@zhenhua-ovs-1 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:33:54:b8 brd ff:ff:ff:ff:ff:ff
    inet 10.22.19.12/24 brd 10.22.19.255 scope global noprefixroute dynamic eth0
       valid_lft 77582sec preferred_lft 77582sec
    inet6 fe80::f816:3eff:fe33:54b8/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:07:50:a8:a2 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

ovs-vswitched.log shows
```
[root@zhenhua-ovs-1 ~]# tail -n 20 /var/log/openvswitch/ovs-vswitchd.log 
2018-09-07T06:55:51.365Z|00026|ofproto|ERR|failed to open datapath br-int: No such file or directory
2018-09-07T06:55:51.365Z|00027|bridge|ERR|failed to create bridge br-int: No such file or directory
2018-09-07T07:20:11.624Z|00028|netlink_socket|INFO|netlink dump request error (No such file or directory)
2018-09-07T07:20:11.625Z|00029|dpif|WARN|failed to enumerate system datapaths: No such file or directory
2018-09-07T07:20:11.625Z|00030|dpif|WARN|failed to create datapath ovs-system: No such file or directory
2018-09-07T07:20:11.625Z|00031|ofproto_dpif|ERR|failed to open datapath of type system: No such file or directory
2018-09-07T07:20:11.625Z|00032|ofproto|ERR|failed to open datapath br-int: No such file or directory
2018-09-07T07:20:11.625Z|00033|bridge|ERR|failed to create bridge br-int: No such file or directory
2018-09-07T07:20:40.888Z|00034|netlink_socket|INFO|netlink dump request error (No such file or directory)
2018-09-07T07:20:40.888Z|00035|dpif|WARN|failed to enumerate system datapaths: No such file or directory
2018-09-07T07:20:40.888Z|00036|dpif|WARN|failed to create datapath ovs-system: No such file or directory
2018-09-07T07:20:40.888Z|00037|ofproto_dpif|ERR|failed to open datapath of type system: No such file or directory
2018-09-07T07:20:40.888Z|00038|ofproto|ERR|failed to open datapath br-int: No such file or directory
2018-09-07T07:20:40.888Z|00039|bridge|ERR|failed to create bridge br-int: No such file or directory
2018-09-07T07:21:16.756Z|00040|netlink_socket|INFO|netlink dump request error (No such file or directory)
2018-09-07T07:21:16.756Z|00041|dpif|WARN|failed to enumerate system datapaths: No such file or directory
2018-09-07T07:21:16.756Z|00042|dpif|WARN|failed to create datapath ovs-system: No such file or directory
2018-09-07T07:21:16.756Z|00043|ofproto_dpif|ERR|failed to open datapath of type system: No such file or directory
2018-09-07T07:21:16.756Z|00044|ofproto|ERR|failed to open datapath br-int: No such file or directory
2018-09-07T07:21:16.756Z|00045|bridge|ERR|failed to create bridge br-int: No such file or directory
[root@zhenhua-ovs-1 ~]# 
``` 

ovs shows there is a br-int bridge.
```
[root@zhenhua-ovs-1 ~]# ovs-vsctl show
aabc712d-b6a0-4ed1-a083-2eda28643c92
    Bridge br-int
        fail_mode: secure
        Port br-int
            Interface br-int
                type: internal
        Port "k8s-zhenhua-ovs"
            Interface "k8s-zhenhua-ovs"
                type: internal
    ovs_version: "2.10.90"
[root@zhenhua-ovs-1 ~]# brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		8000.02420750a8a2	no
```

I am running ovs verion of 2.10.90
```
[root@zhenhua-ovs-1 ~]# ovs-vsctl --version
ovs-vsctl (Open vSwitch) 2.10.90
DB Schema 7.16.1
```

**Comment by shettyg** [comment]
It looks like something went wrong. You are using the master branch and it is possible that there is a bug. Would you mind using the released branch 2.10 instead?

i.e 
git checkout -b 2.10_local origin/branch-2.10

**Comment by ZhangZhenhua** [comment]
Thank you very much for your following up. @shettyg . Branch-2.10 works.

**Comment by lanoxx** [comment]
I started seeing this exact same issue today, but on Windows instead of Linux. 

My OVS tools show version 2.9.4. The issue appeared after a reboot of the node. Before the reboot the interface k8s-*** was correctly established.

Pods were already running on the node and could ping local overlay IPs. But traffic was not being sent through the overlay network to other overlay IPs. I was trying to debug this issue and rebooted the node, then this issue appeared.

Is there any way I can debug this problem further?

I used the following installer to install the node yesterday: https://cloudbase.it/downloads/openvswitch-hyperv-installer-beta.msi

**Comment by lanoxx** [comment]
To be more precise I used the Ansible scripts of ovn-kubernetes which use the above mentioned installer. 

Is there already a newer version available for Windows?

**Comment by lanoxx** [comment]
I was able to solve this, it happend because the HnsNetwork somehow got deleted. Recreating it solved the problem. It might be a good idea to have a check in ovnkube to check if the HnsNetwork exists and give a more descriptive error message.

**Comment by aserdean** [comment]
`ovs-dpctl show` also please include the windows OS version.

**Comment by lanoxx** [comment]
The node is running Windows Server 2019 (desktop edition), `winver` shows Version 1809 (OS Build 17763.107).

`ovs-dpctl show`:

    system@ovs-system:
        lookups: hit:7670 missed:1675 lost:0
        flows: 37
        port 1: vEthernet (Ethernet 3) (internal)
        port 2: Ethernet 3
        port 3: genev_sys_6081 (geneve: packet_type=ptap)
        port 4: k8s-edgeapplian (internal)
        port 7: br-int (internal)
        port 8: default_win-webserver-68b746fd98-ckwpg (internal)

I have put ovnkube onto a VPN tunnel and I am thinking that when the tunnel is destroyed the HNS network is deleted, that might explain why it wasn't there anymore after the reboot.

**Comment by aserdean** [comment]
> I was able to solve this, it happend because the HnsNetwork somehow got deleted. Recreating it solved the problem. It might be a good idea to have a check in ovnkube to check if the HnsNetwork exists and give a more descriptive error message.

Odd https://github.com/openvswitch/ovn-kubernetes/blob/9f4b960c43074f12806c466ce2da0c0f942babe3/go-controller/pkg/cni/helper_windows.go#L52 should have popped up.

Since you are running 1809 please make sure you have this KB applied: https://support.microsoft.com/en-us/help/4482887/windows-10-update-kb4482887 .
If you do not external HNS networks are not persistent across reboots.

I will send out a PR to document it.

**Comment by lanoxx** [comment]
After installing the updates, the version is now *17763.404*. I reran the Ansible scripts and now the k8s-*** interface is in state "Media disconnected" and ovn-kubernetes-node is failing with the same error.

When I run `ovs-vsctl list interface k8s-***` it lists the following error":

> could not add network device k8s-*** to ofproto (Invalid argument)

**Comment by aserdean** [comment]
I'm guessing it couldn't re-add the interface because of a dangling adapter.
Can you paste the output of: `Get-NetAdapter -IncludeHidden` and also `ovs-dpctl show`

**Comment by lanoxx** [comment]
`Get-NetAdapter -IncludeHidden`:

    Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
    ----                      --------------------                    ------- ------       ----------             ---------
    Local Area Connection* 1  WAN Miniport (SSTP)                          18 Disconnected                            0 bps
    Local Area Connection* 6  WAN Miniport (GRE)                           17 Disconnected                            0 bps
    Local Area Connection* 7  WAN Miniport (IP)                            16 Up                                      0 bps
    vSwitch (external)        Hyper-V Virtual Switch Extension Ada...      34 Up                                    10 Gbps
    Local Area Connection* 8  WAN Miniport (IPv6)                          15 Up                                      0 bps
    Local Area Connection* 2  WAN Miniport (IKEv2)                         14 Disconnected                            0 bps
    Local Area Connection* 5  WAN Miniport (PPPOE)                         13 Disconnected                            0 bps
    Local Area Connection* 3  WAN Miniport (L2TP)                          12 Disconnected                            0 bps
    Teredo Tunneling Pseud...                                              11 Not Present                             0 bps
    k8s-***                   Hyper-V Virtual Ethernet Adapter #2          10 Disconnected 00-15-5D-E7-B8-C7        10 Gbps
    default_win-webserver-... Hyper-V Virtual Ethernet Adapter #3          42 Disabled     00-15-5D-18-3A-F8       100 Mbps
    br-int                    Hyper-V Virtual Ethernet Adapter #5          44 Disabled     00-15-5D-18-35-AC       100 Mbps
    default_win-webserver-... Hyper-V Virtual Ethernet Adapter #4          43 Disabled     00-15-5D-18-39-35       100 Mbps
    Ethernet 2                Intel(R) Ethernet Connection (2) I21...       9 Up           4C-52-62-23-AB-AF         1 Gbps
    default_win-webserver-... Hyper-V Virtual Ethernet Adapter #6          45 Disabled     00-15-5D-18-31-C5       100 Mbps
    Microsoft IP-HTTPS Pla...                                               8 Not Present                             0 bps
    vEthernet (Ethernet 3)    Hyper-V Virtual Ethernet Adapter             20 Up           00-FF-05-30-1A-32       100 Mbps
    Ethernet (Kernel Debug... Microsoft Kernel Debug Network Adapter        7 Not Present                             0 bps
    Ethernet                  Intel(R) I210 Gigabit Network Connec...       6 Disconnected 4C-52-62-17-6C-BA          0 bps
    Local Area Connection* 4  WAN Miniport (PPTP)                           5 Disconnected                            0 bps
    6to4 Adapter                                                            4 Not Present                             0 bps
    Ethernet 3                TAP-Windows Adapter V9                        3 Up           00-FF-05-30-1A-32       100 Mbps
    Local Area Connection* 9  WAN Miniport (Network Monitor)                2 Up                                      0 bps

`ovs-dpctl show`:

    system@ovs-system:
        lookups: hit:40857 missed:6179 lost:0
        flows: 127
        port 1: vEthernet (Ethernet 3) (internal)
        port 2: Ethernet 3
        port 3: genev_sys_6081 (geneve: packet_type=ptap)
        port 4: default_win-webserver-edge-d6f9ff4bf-gsnjj (internal)
        port 5: default_win-webserver-edge-d6f9ff4bf-bkwtz (internal)
        port 6: br-int (internal)
        port 7: default_win-webserver-68b746fd98-ckwpg (internal)

**Comment by aserdean** [comment]
> k8s-***                   Hyper-V Virtual Ethernet Adapter #2          10 Disconnected 00-15-5D-E7-B8-C7

😞 can you remove it via device manager and rerun the ansible scripts?

**Comment by lanoxx** [comment]
Deleting the interface and rerunning the Ansible scripts brought the interface back in a connected state. Afterwards I rebooted the node and now I am happy to see that the k8s-*** interface survived the reboot. Thanks a lot for the help.

Now I can go back to debugging my connectivity issues to find out why I cannot ping other overlay IPs from this node.

**Comment by aserdean** [comment]
> Deleting the interface and rerunning the Ansible scripts brought the interface back in a connected state. Afterwards I rebooted the node and now I am happy to see that the k8s-*** interface survived the reboot. Thanks a lot for the help.

Anytime!

> Now I can go back to debugging my connectivity issues to find out why I cannot ping other overlay IPs from this node.

If you need help feel free to ping me via IRC #openvswitch on irc.freenode.net.
