### ISSUE TITLE
Document usage of DNS servers (sky-dns).

### ISSUE THREAD

**Issue by shettyg** [openvswitch/ovn-kubernetes#43]
Some time needs to be spent to test and document usage of sky-dns.

**Comment by salv-orlando** [comment]
I am doing that for another k8s integration proejct. I might help here as well.

**Comment by rajatchopra** [comment]
With kubelet option '--cluster-domain' one can set the appropriate nameservers and search paths that will be merged with host's resolv.conf!
The only issue (that need not be fixed) is that the OVN gateway used for reaching the nameserver should not be the same as the gateway's physical IP.
Closing this issue.
