### ISSUE TITLE
External SDN Controller

### ISSUE THREAD

**Issue by yvzsrt** [openvswitch/ovn-kubernetes#430]
In your solution, every hypervisor has a ovn-controller. So, it means every hypervisor has its own SDN controller, right?

Is it possible to manage SDN network with a central external SDN controller such as Onos or Opendaylight?

**Comment by shettyg** [comment]
>In your solution, every hypervisor has a ovn-controller. So, it means every hypervisor has its own SDN controller, right?

That is only partially true. There are two central databases. The first one is populated by the user (ovn-kubernetes is the user in this case). The second is populated by ovn-northd daemon. This ovn-northd daemon is what you can call as a central controller.  This does most of the work. ovn-controller in all the nodes just gets entries from this database and converts it into openflow flows in OVS.

>Is it possible to manage SDN network with a central external SDN controller such as Onos or Opendaylight?

No. Not with ovn-kubernetes. This needs OVN.

**Comment by yvzsrt** [comment]
Thanks @shettyg, i need more clarification. Our entire goal is to setup a kubernetes and manage its network via openflow. Is it possible to setup such system? 

You mentioned, that needs ovn but i couldn't get it? Could you please give some detailed information?

**Comment by shettyg** [comment]
>You mentioned, that needs ovn but i couldn't get it? Could you please give some detailed information?

I just meant to say that, this Github repository only works with OVN. OVN does program openflow in OVS. 

Kubernetes can work without OVN. But that is out of scope of this Github repo.
