### ISSUE TITLE
Missing hostname in open_vswitch . external-ids, which leads to error in ovn-nbctl startup

### ISSUE THREAD

**Issue by cn-mayank** [openvswitch/ovn-kubernetes#443]
I tried to setup the cluster via playbook in contrib section and I try to setup on aws.

I observed that my containers were not able to access internet. I had setup a cluster previously using same playbook and infra where containers were able to access internet. 

When debugging, I found that on linux-minion node 

`ovn-nbctl list logical_router ovn-nbctl: unix:/var/run/openvswitch/ovnnb_db.sock: database connection failed (No such file or directory)`

Also I found some error logs as follows:
`Oct 03 07:44:10 ip-10-224-142-226 ovs-vsctl[31345]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --no-wait set Open_vSwitch . external-ids:hostname=
Oct 03 07:44:10 ip-10-224-142-226 ovs-vsctl[31345]: ovs|00002|db_ctl_base|ERR|external-ids:hostname=: argument does not end in "=" followed by a value.`

When i run the command `ovs-vsctl get open_vswitch . external_ids`, I get following output

{
"k8s-api-server"="http://10.224.142.226:8080",
 "k8s-api-token"="xxxx_a_long_token", 
ovn-encap-ip="10.224.142.226", 
ovn-encap-type=geneve, 
ovn-nb="tcp:10.224.134.90:6641", 
ovn-remote="tcp:10.224.134.90:6642", 
ovn-remote-probe-interval="100000", 
rundir="/var/run/openvswitch", 
system-id="f0b523fd-1984-48c5-8b87-0595ff29d34a"
}

I destroyed the infrastructure and tried again multiple times, even tried with older commits which definitely were working but everytime now I am getting this issue. Request for some pointers on how to resolve. Thanks!

**Comment by shettyg** [comment]
>ovn-nbctl list logical_router ovn-nbctl: unix:/var/run/openvswitch/ovnnb_db.sock: database connection failed (No such file or directory)

This is probably because you did not use sudo?

**Comment by cn-mayank** [comment]
I was logged in as root so sudo should not be problem. Problem is internet access from containers have stopped working and with my very limited grasp of ovn-k8s, i thought this might be issue as seen in logs.

**Comment by shettyg** [comment]
And you rant the command in master node?

Were pods able to ping each other across hosts?

I guess, you no longer have the setup?

**Comment by cn-mayank** [comment]
The command failed on linux-minion node. It ran successfully on master node.
I did not check for pods being able to ping each other. I will quickly recreate the setup, test and update here as it is actually reproducible issue for me.

**Comment by shettyg** [comment]
>The command failed on linux-minion node. It ran successfully on master node.
It is only supposed to run correctly on master node.

Once you have the reproduction, do print in the o/p of `ovn-nbctl list logical_router_static_route`
and `ovn-nbctl show`.

From the nodes, try to ping to your pod IPs (pods in the same node as well as other nodes). 

From inside the pod, try to ping the nexthop of your VM. This IP will also be seen in the o/p of  `ovn-nbctl list logical_router_static_route` with output_port set and ip_prefix is 0.0.0.0/0

**Comment by cn-mayank** [comment]
Hi, recreated the setup and reproduced the issue.
1. From the nodes, i am able to ping the pods successfully.
2. Pods are able to serve https requests across hosts. 
3. Output of `ovn-nbctl list logical_router_static_route` and `ovn-nbctl show` is same `ovn-nbctl: unix:/var/run/openvswitch/ovnnb_db.sock: database connection failed (No such file or directory)`. Could not ping ip of next-hop as command for determining didn't work

**Comment by shettyg** [comment]
>Output of ovn-nbctl list logical_router_static_route and ovn-nbctl show is same ovn-nbctl: unix:/var/run/openvswitch/ovnnb_db.sock: database connection failed (No such file or directory). Could not ping ip of next-hop as command for determining didn't work

You have to run this on master.

**Comment by cn-mayank** [comment]
Yes, you are absolutely correct! I am able to ping the actual ip address of google.com but not google.com. I will add an edit in the comments above .

**Comment by shettyg** [comment]
You can look in /etc/resolv.conf and see the IPs listed there. What are those IPs? Can you ping them? May be the kubernetes cluster DNS pod is not running?

**Comment by cn-mayank** [comment]
From within the pod, output of /etc/resolv.conf
```
root@webserverlin2-798dbcf665-6xz6x:/# cat /etc/resolv.conf 
nameserver 10.0.9.10
search default.svc.cluster.local svc.cluster.local cluster.local devfactory.local
options ndots:5
```

From master node:
```
root@ip-10-224-131-107:~# cat /etc/resolv.conf 
domain devfactory.local
search devfactory.local
nameserver 10.212.70.10
nameserver 10.212.71.10
nameserver 10.224.0.2
nameserver 8.8.8.8
```

From within the pod, I am not able to ping `10.0.9.10` but i can ping `10.212.70.10`

**Comment by shettyg** [comment]
>From within the pod, I am not able to ping 10.0.9.10 but i can ping 10.212.70.10

That explains why DNS resolution does not work. What is 10.0.9.10?

**Comment by cn-mayank** [comment]
No such entity in my infrastructure/subnet and looks like kubernetes specific. I will try to find out its source. Thanks!

**Comment by cn-mayank** [comment]
Hi @shettyg ,
I found the source of `10.0.9.10`, it is set in the ovn-kubernetes repo itself as a playbook variable [here](https://github.com/openvswitch/ovn-kubernetes/blob/7b69f2016cc82164fe55a171dbbeffc92631dae7/contrib/inventory/group_vars/all#L14). 
I am not sure why it has suddenly stopped working, because i have used the playbook in past and it worked well. Any pointers on how to proceed ?
Also I am not sure if the playbook in the contrib section also sets up `kube-dns` ?

**Comment by cn-mayank** [comment]
Hey guys, I attempted to setup on google cloud engine, also tried changing kubernetes version but facing the same error. Would really appreciate any pointers to proceed.
Thanks!

**Comment by alinbalutoiu** [comment]
Hi @cn-mayank , the playbooks are not deploying ``kube-dns`` yet unfortunately. You could try to set it up manually in the meanwhile until the support is added in the playbooks. Besides the DNS issue, do you have any other issues? Also, thanks for trying it out!

**Comment by cn-mayank** [comment]
Hi @alinbalutoiu , what is the significance of ip `10.0.9.10` which is coded in the playbook [here](https://github.com/openvswitch/ovn-kubernetes/blob/7b69f2016cc82164fe55a171dbbeffc92631dae7/contrib/inventory/group_vars/all#L14). This ip gets supplied to kubelet command as argument as well and is not reachable from container. 

Also do you thing `ovn-nbctl list logical_router ovn-nbctl: unix:/var/run/openvswitch/ovnnb_db.sock: database connection failed (No such file or directory)` is related to dns issue ?

**Comment by alinbalutoiu** [comment]
Hi @cn-mayank , that is the IP of the dns service which is not getting created by the playbooks at the moment. 
``ovn-nbctl list logical_router`` - are you running this command from one of the master nodes as root?

**Comment by cn-mayank** [comment]
Thanks for the clarification! I will setup dns manually to proceed further
