### ISSUE TITLE
Support active standby

### ISSUE THREAD

**Issue by Yukariko** [openvswitch/ovn-kubernetes#445]
I want to set active-standby model for replicated pods.
All packets are sent to the active pod,  and other pods are waited.
I think the solution is bonding ports.
Does ovnkube support active-standby?
Is it possible to apply this model?

**Comment by shettyg** [comment]
@Yukariko 

ovn-kubernetes does not support such a thing right now. A possible way to implement such a thing in kubernetes is to have your service point to only one pod. And then change the pod when your desired event happens. But the monitoring of the desired event has to be external to ovn.

**Comment by Yukariko** [comment]
Thanks a lot.
