### ISSUE TITLE
Ansible scripts fail starting startup.ps1 on Windows Nodes.

### ISSUE THREAD

**Issue by adelina-t** [openvswitch/ovn-kubernetes#459]
Running ansible scripts on env with Windows minions fails at task:

`windows/kubernetes : OVS Docker network setup | Make startup script Run`

 with:

`2018-10-22 08:03:19,437 p=5226 u=ubuntu |  fatal: [win-seq-min1]: FAILED! => {"changed": true, "cmd": "$RegPath = \"HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\"\n # HKCU to run after the user logs in\n $RegROPath = \"HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\"\n\n $script = \"C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe -noexit C:\\startup.ps1\"\n\n Set-ItemProperty $RegPath \"AutoAdminLogon\" -Value \"1\" -type String\n Set-ItemProperty $RegPath \"DefaultUsername\" -Value \"admin\" -type String\n Set-ItemProperty $RegPath \"DefaultPassword\" -Value \"s9SVkMKW9DpW8ZNXcdcI\" -type String\n Set-ItemProperty $RegPath \"AutoLogonCount\" -Value \"1\" -type DWord\n Set-ItemProperty $RegROPath \"OVN_Init_Node\" -Value \"$script\" -type String", "delta": "0:00:01.105843", "end": "2018-10-22 08:03:19.259886", "msg": "non-zero return code", "rc": 1, "start": "2018-10-22 08:03:18.154043", "stderr": "Set-ItemProperty : Cannot find path 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run' because it does not exist.\r\nAt line:11 char:2\r\n+  Set-ItemProperty $RegROPath \"OVN_Init_Node\" -Value \"$script\" -type S ...\r\n+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (HKCU:\\SOFTWARE\\...rentVersion\\Run:String) [Set-ItemProperty], ItemNotFo \r\n   undException\r\n    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand", "stderr_lines": ["Set-ItemProperty : Cannot find path 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run' because it does not exist.", "At line:11 char:2", "+  Set-ItemProperty $RegROPath \"OVN_Init_Node\" -Value \"$script\" -type S ...", "+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : ObjectNotFound: (HKCU:\\SOFTWARE\\...rentVersion\\Run:String) [Set-ItemProperty], ItemNotFo ", "   undException", "    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand"], "stdout": "", "stdout_lines": []}`

Ansible user: Admin ( not built in Administrator )

NOTE: 

1. It is not consistent for every deployment. Sometimes it passes just fine.
2. On deployments where it does fail, running playbook again will pass.

Extra info: 

Minion Nodes Windows Server 1803. 
Using scripts with this PR: 
https://github.com/openvswitch/ovn-kubernetes/pull/450 cherry-picked

**Comment by alinbalutoiu** [comment]
Hello! Could you please share the output of the following command from that node?
```
Get-Item -Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
```
On deployments where it does fail and you run again, does the whole playbook pass and the cluster works?
Also, would it be possible to share the whole output of the playbook? Thanks!

**Comment by adelina-t** [comment]
@alinbalutoiu 

Unfortunately I don't have that machine anymore. But from memory I can say that after a successful RDP login, running that command  works, as in, the key exists.

> On deployments where it does fail and you run again, does the whole playbook pass and the cluster works?

It passes this particular task. It fails further along the line.

> Also, would it be possible to share the whole output of the playbook? Thanks!

https://www.dropbox.com/s/xvlz8awqn80w5na/win-seq.log?dl=0

NOTE: There are a bunch of runs/reruns in the same log file, you might need to dig a little.

**Comment by alinbalutoiu** [comment]
Thanks for the playbook output, that was really helpful. Could you please try now with the updated #450 ? It should fix your issue.

**Comment by aserdean** [comment]
@adelina-t the PR got merged. Can you please try with the master branch and let us know if the issue got fixed?

**Comment by adelina-t** [comment]
@aserdean Tested it by cherry-picking at the beginning of last week and it seemed fine. Will try again for master and confirm.

**Comment by aserdean** [comment]
Thanks.

**Comment by rajatchopra** [comment]
Closing out this issue. Please re-open if the issue still persists in master.
