### ISSUE TITLE
Different minions end up having the same ovn_host_subnet

### ISSUE THREAD

**Issue by alinbalutoiu** [openvswitch/ovn-kubernetes#463]
Deploying with ansible playbooks an environment with one linux and one windows minion node will result in:
```
# kubectl get nodes
NAME              STATUS   ROLES    AGE     VERSION
k8s-minion-lin    Ready    <none>   41m     v1.12.0
win-dtb9rfu5o7n   Ready    <none>   6m49s   v1.12.0
# kubectl describe node k8s-minion-lin | grep ovn_host_subnet
                    ovn_host_subnet: 10.0.0.0/24
# kubectl describe node win-dtb9rfu5o7n | grep ovn_host_subnet
                    ovn_host_subnet: 10.0.0.0/24
```
The subnets assigned should be different.

**Comment by rajatchopra** [comment]
@JacobTanenbaum Can you take a look at this? Seems like after your multiple cidr change.

**Comment by alinbalutoiu** [comment]
Probably will help to debug, the current workaround is to remove one node and add it again, which will have ``10.0.2.0/24`` assigned to it. Cluster subnet is ``10.0.0.0/16``.

**Comment by girishmg** [comment]
We are seeing this as well. I am using Daemonsets and running on top of 0906c470c7e3b4de4929e1fd658626feffca7f62. 

`
$ kubectl get nodes -o yaml |grep -i cidr
    podCIDR: 192.168.1.0/24
    podCIDR: 192.168.0.0/24
    podCIDR: 192.168.2.0/24
$ kubectl get nodes -o yaml | grep ovn_host
      ovn_host_subnet: 192.168.0.0/24
      ovn_host_subnet: 192.168.1.0/24
      ovn_host_subnet: 192.168.0.0/24
`

**Comment by lanoxx** [comment]
I can also confirm this, my Linux node which I setup today has been assigned the same subnet as one of my Windows nodes.

**Comment by shettyg** [comment]
@JacobTanenbaum @rajatchopra Were you planning to look at this? Should we revert the patches till we get a hold of the problem?

**Comment by rajatchopra** [comment]
@lanoxx  @girishmg  Is there a definite way of reproducing this so far that you noticed? 
I have just given a glance to the code and I could not catch a problem. I have tried removing a node and re-adding it several times, but I could not reproduce the issue.

**Comment by aserdean** [comment]
Fixed with https://github.com/openvswitch/ovn-kubernetes/pull/509 .
