### ISSUE TITLE
prefix the name of the distributed router with DR_ (or some such)

### ISSUE THREAD

**Issue by girishmg** [openvswitch/ovn-kubernetes#484]
In the OVN topology that is build, the name of the K8s master node's Logical Switch and the name of the distributed router for the entire K8s cluster are same. For example: if the hostname of the K8s master node is `k8s-ubuntu-master`, then we will have two OVN resources -- one logical switch and one logical router -- that will be named as `k8s-ubuntu-master`.

This causes some issues while displaying the logical flows for the OVN resources as can be seen below (just an example of one of the issues).

```
 # ovn-sbctl lflow-list k8s-ubuntu-master
 ovn-sbctl: multiple rows in Datapath_Binding match "k8s-ubuntu-master"
```

To resolve the above problem, one would need to resort to UUID of the OVN resource. For everything else we will be using the names, but just for the two aforementioned resources we will have to resort to UUIDs.

So, it is better to rename the Logical router to `DR_<hostname_of_the_master>`.  I am raising this issue to capture the change we are working on.

Please comment on the name `DR_<hostname_of_the_master>`, if you don't feel the name is right.

**Comment by shettyg** [comment]
With OVN HA, "hostname_of_the_master" may not be a good name. How about just "ovn_cluster_router".

**Comment by girishmg** [comment]
ovn_cluster_router sounds better. Thanks @shettyg .

**Comment by girishmg** [comment]
The distributed router is now called ovn_cluster_router
