### ISSUE TITLE
make use of localnet ports in external logical switch that connects to Gateway Routers

### ISSUE THREAD

**Issue by girishmg** [openvswitch/ovn-kubernetes#485]
The external OVN logical switch that connects the OVN l3gateway router (and all of the logical ports behind that gateway router) to underlay/physical network can make us of 'localnet' logical port type.

With the `localnet` logical port, the ovn-controller running on each of the K8s node and master will take care of patching `br-int` to the OVS bridge that has physical port connected to it. We don't need additional logic in ovnkube to add those patch ports ourselves (like we do today).

I understand that setting the port type to be `localnet` by itself is sufficient. We also need to set the localnet port's options field to `network_name=<name_of_network>`. For example: `network_name=physical`. We also need to set the ovn-bridge-mappings on each of the node. All this can be done in the ovnkube since we have all the info from --gateway-* arguments.

Also, I think we may not need the OpenFlow rules that we currently add to gateway OVS bridge on each of the node. ovn-controller on each of the node should push the right OpenFlow rules. (I will need to check on this through some testing).

Currently, we have:
```
       +--------------------------------+
       |      GR_k8s_minion_node1       |
       |       (L3Gateway Router)       |
       +----------------+---------------+
              rtoe-GR_k8s_minion_node1   
                        |                
                        |                
                        |                
              etor-GR_k8s_minion_node1   
       +----------------+---------------+
       |      ext_k8s_minion_node1      |
       | +-----+(Logical Switch)        |
       +-+ VIF +------------------------+
         +--+--+                         
       brenp5s0_k8s_minion_node1         
            |                            
            |                            
            |                            
     -------+---------------             
       underlay network                  
```
I am suggesting that we move to `localnet` model. It will be same except for the type of the port and some less code in ovnkube:
```
       +--------------------------------+
       |      GR_k8s_minion_node1       |
       |       (L3Gateway Router)       |
       +----------------+---------------+
              rtoe-GR_k8s_minion_node1   
                        |                
                        |                
                        |                
              etor-GR_k8s_minion_node1   
       +----------------+---------------+
       |      ext_k8s_minion_node1      |
       |        (Logical Switch)        |
       |+----------+                    |
       ++ localnet +--------------------+
        +---+------+                     
     brenp5s0_k8s_minion_node1           
            |                            
            |                            
     -------+---------------             
       underlay network                  
```

**Comment by shettyg** [comment]
>Also, I think we may not need the OpenFlow rules that we currently add to gateway OVS bridge on >each of the node. ovn-controller on each of the node should push the right OpenFlow rules. (I will >need to check on this through some testing).

1. This likely does not happen. i.e there are no openflow flows added by ovn-controller to the physical bridge.

2. Currently ovnkube programs physical bridge to multiplex mgmt traffic and nodeport traffic. This we will have to continue to do.

The only advantage I see is that, we don't have to create the patch ports in ovnkube and instead ovn-controller will do it.

I think there are complications on how we will need to do gateway routers and handle nodeports. Currently a OVS patch port becomes a interface of gateway router with the router having the same mac address as the physical bridge.  It may all just work with localnet, but will need to be very careful. If upstream OVN changes anything with localnet to handle OpenStack cases, we may get effected unduly downstream.

If the only disadvantage you see is manual creation of patch ports, I don't think it is the worth the need for the change. If there is anything else that I have missed, let me know.

**Comment by girishmg** [comment]
Yes, we will still need to handle OpenFlow rules on the physical bridge to multiplex mgmt traffic and nodeport traffic. There is no around it, and we will need it.

The thing is that there is a perfect abstraction/construct in OVN called localnet port which represents what we are doing. So, it is not the manual creation of patch ports, but the fact that we are not using that OVN construct to achieve what we want is little unsettling :).

Also, if the underlay or physical network is a VLAN based (say 33), then I think we need the port type to be localnet? In that case we can set the tag_request to `33` and all the outgoing traffic will be tagged with VLAN ID 33. From ovn-nb(5) manpage

```
When  type  is  set to localnet or l2gateway, this can be set to indicate that the port represents a  connection  to  a  specific VLAN  on  a  locally  accessible network. The VLAN ID is used to  match incoming traffic and is also added to outgoing traffic.
```

**Comment by shettyg** [comment]
>The thing is that there is a perfect abstraction/construct in OVN called localnet port which represents what we are doing. So, it is not the manual creation of patch ports, but the fact that we are not using that OVN construct to achieve what we want is little unsettling

ovn-controller will treat the packets coming from a patch port as a switch port. Our's is a router port. So it likely won't work.

**Comment by shettyg** [comment]
>ovn-controller will treat the packets coming from a patch port as a switch port. Our's is a router port. So it likely won't work.

Scratch that, I am wrong. Try and see whether it works and then we can decide.

**Comment by girishmg** [comment]
@shettyg localnet port type works fine, and I tested it. A small caveat is that ovn-node container in our ovnkube daemonset should now wait for ovn-controller to be up and running before it proceeds. So, we will need wait_for_ovn_controller() check in ovnkube.sh in start_node().

**Comment by dcbw** [comment]
@girishmg could you explain a bit more where the NAT would happen for the localnet port?

**Comment by girishmg** [comment]
@dcbw The NAT will occur on the L3Gateway port i.e., rtoe-GR_k8s_minion_node1. This is just like how it happens today in the non-localnet case as well. The packet will be SNAT'ed before it enters the external logical switch for a given minion.
