### ISSUE TITLE
Playbook: Use synchronize instead of fetch to sync files

### ISSUE THREAD

**Issue by lanoxx** [openvswitch/ovn-kubernetes#494]
Currently the playbook uses the Ansible `fetch` module to fetch Kubernetes binaries in `roles/linux/kubernetes/tasks/fetch_k8s_binaries.yml`, this module has a known issue that it needs a lot of memory when transfering files. On my test machines the memory (2GB) was not enough and the playbook kept failing. I changed the `fetch` module to `synchronize` and was able to resolve this problem:

     - name: Kubernetes bins | fetch Linux binaries to the ansible host
    -  fetch:
    -    fail_on_missing: yes
    -    flat: yes
    +  synchronize:
    +    mode: pull
         src: "{{kubernetes_binaries_info.tmp_download_path}}/kubernetes/server/kubernetes/server/bin/{{item}}"
         dest: "{{ansible_tmp_dir}}/{{item}}"
       with_items:
    @@ -11,9 +10,8 @@
         - "{{kubernetes_binaries.linux_minion}}"

     - name: Kubernetes bins | fetch Windows binaries to the ansible host
    -  fetch:
    -    fail_on_missing: yes
    -    flat: yes
    +  synchronize:
    +    mode: pull
         src: "{{kubernetes_binaries_info.tmp_download_path}}/kubernetes/node/bin/{{item}}"
         dest: "{{ansible_tmp_dir}}/{{item}}"

**Comment by alinbalutoiu** [comment]
Looks good, thanks! Do you have the time to submit a pull request for this change?
