### ISSUE TITLE
Ansible: support custom URL for k8s binaries

### ISSUE THREAD

**Issue by papagalu** [openvswitch/ovn-kubernetes#495]
Right now the URL is hardcoded in ovn-kubernetes/contrib/roles/linux/kubernetes/ubuntu.yml

the prefix should be configurable
and also add the env variable for this task:
https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/roles/linux/kubernetes/tasks/download_k8s_binaries.yml#L47
the env var should be: KUBERNETES_RELEASE_URL

**Comment by alinbalutoiu** [comment]
The URL is not hardcoded, it's in the file which contains variables associated with that specific role, it follows the structure from here: https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html
If you want to have it in an easier to find place, you could put it in the main playbook file, similar to: https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/ovn-kubernetes-cluster.yml#L72
And then just use that variable in the code.

**Comment by papagalu** [comment]
Our original issue should be fixed by PR #535 
I am closing the issue since it's not needed anymore.
