### ISSUE TITLE
Document non gateway modes

### ISSUE THREAD

**Issue by theonlydoo** [openvswitch/ovn-kubernetes#50]
> Gateway nodes are needed for North-South connectivity. OVN does have support for multiple gateway nodes, but this documentation only talks about one gateway node

Other use cases can be interesting too.

**Comment by shettyg** [comment]
>Other use cases can be interesting too.

What cases are you referring to? Multiple gateways? Or something else?

**Comment by theonlydoo** [comment]
Multiple gateway could be nice, failover w/ heartbeat on exit node also. 
But I had in mind simple overlay networking w/ no designated exit node

**Comment by shettyg** [comment]
The pull request #55 takes care of multiple gateways as well as exit via every node (which is effectively gateways in every node).  The general problem with gateways in every node is that when nodePort gets assigned by k8s, all the nodes should have it available which I am not sure how tricky it is to debug.  The nice thing though is that local traffic can exit from the same node.

But with the eventual goal of Intel DPDK based gateways, it will be interesting to see which one is better.

The heart-beat feature is important, but it will likely be a while before it gets implemented (unless someone volunteers)

**Comment by theonlydoo** [comment]
Cheers!
