### ISSUE TITLE
Ansible: Update the documentation with the ports used

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovn-kubernetes#500]
When deploying on clouds people need to open the ports used by the agents in order to communicate.

Document the list of ports needed to achieve the above.

**Comment by lanoxx** [comment]
Ports I needed to open so far are:

**OVN Related Ports:**

 * GENEVE: `6081` or alternatively with STT: `7471`
 * OVN Database Port: `6641 - 6642`

**Kubernetes Ports:**

 * Kubernetes Service Ports: `30000 - 32767`
 * kubelet: `10250 - 10252`
 * Kubernetes API Server Port: `8080`, `443`

**Ansible related ports:**

 * WinRM via HTTPS: `5986` (for HTTP also `5985`)
 * SSH: `22`

Further Ports, non OVN related:

 * Windows RDP Port: `3389`
 * For debugging opening ICMP ports are useful too.

**Comment by lanoxx** [comment]
I accidentally configured the Geneve Ports as TCP instead of UDP in the Firewall and that obviously caused problems. So I updated my list above and explicitly added TCP or UDP for each port.
