### ISSUE TITLE
panic: Windows is not supported as a gateway node

### ISSUE THREAD

**Issue by lanoxx** [openvswitch/ovn-kubernetes#513]
I have updated my playbook to use the latest patches from master and ran it again on a completely new set of nodes (master,Linux and Windows). The playbook ran through but in the `ovn-kubernetes-node.log` I now find the following error:

    type .\ovn-kubernetes-node.log
    time="2018-11-25T09:22:54Z" level=info msg="Node ec2amaz-lnpvaj6 ready for ovn initialization with subnet 10.245.2.0/24"
    panic: Windows is not supported as a gateway node

Using `kubectl get nodes` the Windows node has a status of not ready and states that CNI is not configured.

**Comment by alinbalutoiu** [comment]
Did you clear the cache folder from inside the ansible folder? It looks like the binary running is still the old one, as in the new code there is no log related to ``Windows is not supported as a gateway node`` anymore.

**Comment by lanoxx** [comment]
That was indeed the problem. Sorry for the noise.
