### ISSUE TITLE
RunOVNNbctlHA() makes an incorrect assumption on which scheme to use

### ISSUE THREAD

**Issue by girishmg** [openvswitch/ovn-kubernetes#525]
RunOVNNbctlHA incorrectly assumes that if a single server is provided for ovn-nb, then OVN NB is available locally and it switches the connection to use AF_UNIX. It could be that the OVN DBs are  external to K8s cluster and may not be available locally on the master node (or that the OVN DB is configured as active-standby or active-backup nodes outside of K8s cluster)

We should remove switching to AF_UNIX connection in RunOVNNbctlHA(), @shettyg ?

**Comment by shettyg** [comment]
It is a fair concern. The reason it was kept to Unix domain was that it is more reliable.

**Comment by dcbw** [comment]
Ran into this yesterday too. Couldn't we just assume that if the DB is colocated on the same machine, that ovnkube would be passed "--northdb=unix" or whatever? eg if ovnkube is configured with a socket path then obviously the db is local. If it's an IP, then assume it's remote.

**Comment by girishmg** [comment]
@dcbw yes we default to OvnDBSchemeUnix if one doesn't specify --nb-address or --sb-address during ovnkube invocation.

@shettyg I am going to remove this API  and instead just use RunOVNbctl() that handles ssl, tcp, and unix connections very well.

**Comment by girishmg** [comment]
fixed by https://github.com/openvswitch/ovn-kubernetes/commit/8b454bb190a274d60dcd58f9d5cf2a3811c8a82b
