### ISSUE TITLE
Race condition between creation of logical_switch and port addition to logical_switch

### ISSUE THREAD

**Issue by girishmg** [openvswitch/ovn-kubernetes#531]
Following logical OVN constructs are required for OVN K8s Pod networking
  1. Distributed Router
  2. Join Switch
  3. Logical Switches per node
  4. Logical Switch Ports
  5. Gateway routers and external logical switch
  6. NAT, LB, and so on (this is not important for this discussion)

Today, net-controller creates (1), (2), and (4). The item (3) and (5) above is created by the
ovnkube running on the node itself.

I am seeing a race condition while using Multus CNI + OVN CNI as a default network.
Both Multus and OVN are deployed as daemonsets.

The race condition I am seeing is that the K8s node registers as ‘Ready’ with the Master
since the Multus CNI has configured fine. However, the OVN’s ovnkube-node container
is stuck waiting on OVS daemons to be up and running. So, it has not created a logical
switch yet. In the meantime, since the node is Ready, the pods gets scheduled to this node.

In the net-controller, we try to annotate the pod by adding the logical_switch_port.
However, this fails because the logical_switch is not found for that node. I see errors like:

```
time="2018-11-30T01:14:53Z" level=error msg="Error while creating logical port kube-system_coredns-78fcdf6894-sl5jr stdout: \"\", stderr: \"ovn-nbctl: nd-sjc3a-c17-dgx-08: switch name not found\\n\" (exit status 1)"
time="2018-11-30T01:14:53Z" level=error msg="Error while creating logical port kube-system_coredns-78fcdf6894-jkzxr stdout: \"\", stderr: \"ovn-nbctl: nd-sjc3a-c17-dgx-08: switch name not found\\n\" (exit status 1)"
```

The Pod is not annotated because of above error.  In the meantime, on that node OVN daemonset
Is finally up and running. The OVN CNI waits for the pod annotation and finally gives up. The pod
ends up in Error state. 

Note that the Multus CNI provides with default network readiness indicator which waits for the OVN CNI to be configured before it starts  plugging interfaces into pod. This doesn’t help because Pod annotation happens elsewhere.

I am suggesting that we should create (3) – logical switch --  in net-controller itself. That way, we will have Logical_switch when we need it.

**Comment by rajatchopra** [comment]
Even if we create (3) in net-controller code, we may run into other parts of the race, isn't it?
e.g. the ovnkube cnishim communication not ready.

**Comment by girishmg** [comment]
@rajatchopra yes, that is a separate race condition but it is recoverable error. So, on the OVN node

(1) we write the CNI Config file (but say we have not started the CNIServer yet)
(2) Multus through readiness check indicator (which is 10-ovn-kubernetes.conf) thinks that OVN CNI is ready and calls `ovn_k8s_cni_overaly ADD` and this times out (or some such) since CNIServer is not ready.
(3) POD crashes and restarts
(4) CNIServer is ready
(5) POD now starts with OVN interface plugged in it 

So, this race is definitely orthogonal to the issue I capture above. If we do (3) in net-controller, then all the logical aspects of the OVN will be covered (except for the l3 Gateway part and LB rules and such). 

The only thing that will be then required to do is to do physical plumbing -- creating veth pair, configuring container interface with ip, mac, and gateway addresses, adding the host interface to br-int and adding iface-id. For this part, I don't see any race here.

**Comment by pecameron** [comment]
@girishmg I ran into this in PR 559. I found that setting up /opt/cni/bin/ovn-k8s-cni-overlay after the "ovnkube --node" pidfile is created solves the problem. I wonder if this may help with what you are seeing.

Also, when ovn is removed make sure /opt/cni/bin/ovn-k8s-cni-overlay and /etc/cni/net.d/10-ovn-kubernetes.conf are deleted.
