### ISSUE TITLE
contributing and developing

### ISSUE THREAD

**Issue by dotanalon** [openvswitch/ovn-kubernetes#588]
Hey,
we examining the use of ovn + ovs in our k8s use case,
currently I cant find the architecture documentation regarding this project, we have several things that we dont fully understand like:
* vxlan or geneve endpoints for underlay networks
* the gateway mechanism
   for example I have 1 k8s controller and one node, on the master this is the ovnkube execution:  /usr/bin/ovnkube --cluster-subnet 192.168.0.0/16 --service-cluster-ip-range 10.96.0.0/12 --init-master k8s-master-1.novalocal --nodeport --net-controller
  on the node: /usr/bin/ovnkube --cluster-subnet 192.168.0.0/16 --service-cluster-ip-range 10.96.0.0/12 --nodeport --init-gateways --init-node k8s-node-1.novalocal

this is the ip of the ovs bridge in the k8s node:
```
[root@k8s-node-1 ~]# ip a show dev k8s-k8s-node-1.
13: k8s-k8s-node-1.: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether a6:ba:68:d4:2a:9a brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.2/24 scope global k8s-k8s-node-1.
       valid_lft forever preferred_lft forever
```

but the default GW in the containers are 192.168.2.1 ...

**Comment by dotanalon** [comment]
Thanks,
currently I have issues with the tunneling...
any way to check why nodes not listed in the chassis topology?

```
[root@k8s-master-1 ~]# ovn-sbctl list chassis
_uuid               : fdf9d2b2-58ac-4924-95bf-a6745e574f36
encaps              : [2ff4a160-1ff3-4bdc-b892-40f42c38e702]
external_ids        : {datapath-type="", iface-types="erspan,geneve,gre,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan", ovn-bridge-mappings=""}
hostname            : "k8s-master-1.novalocal"
name                : "aa1665bf-4754-4300-bdcf-4551ced0a14a"
nb_cfg              : 45
vtep_logical_switches: []
```
while there is master and 2 nodes configured
Thanks,

**Comment by aserdean** [comment]
I guess you figured it out:
https://github.com/openvswitch/ovn-kubernetes/issues/589

Do you mind if I close this issue?
