### ISSUE TITLE
Using RBAC with OVN

### ISSUE THREAD

**Issue by lanoxx** [openvswitch/ovn-kubernetes#590]
When RBAC is enabled the OVN tool fail to work correctly, presumable because they cannot authenticate with the apiserver anymore.

I tried binding each node to the system:node cluster role, but it seems that is not enough. Is there any documentation available on using RBAC with OVN-Kubernetes?

Also, I think if the generated SSL certificates would include an `O=` organization property in addition to the common name, it would make it a little easier to set a clusterrolebinding for the nodes. Kubectl treats the organization field as group during authorizations.

**Comment by shettyg** [comment]
The vagrant directory in the repo (setup-master.sh) shows how to use RBAC. e.g: From here: https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-master.sh#L165

**Comment by lanoxx** [comment]
Thanks for the pointer, it was a good reference. I managed to activate RBAC with OVN, in addition to the service role binding, I added the Node Authorization module and had to make the corresponding changes to the `node.pem` certificate (e.g. update username to `system:node:<nodeName>` and add `system:nodes` group) and also had to add the `system:masters` group to the `admin.pem` certificate.
