### ISSUE TITLE
components distribution

### ISSUE THREAD

**Issue by dotanalon** [openvswitch/ovn-kubernetes#591]
from the documentation is not fully clear on which k8s role which ovn or ovs component need to execute:
for example in non HA env which components will run on a k8s node? ovs+ovnkube only or ovn controller also?
Thanks,

**Comment by aserdean** [comment]
For every worker/minion you need the following: `ovsdb-server`, `ovs-vswitchd`, `ovn-controller`, `ovnkube`.

You will need `ovn-northd` which will require two additional ovsdb-servers for the NB/SB database. We usually deploy it where the rest of the main Kubernetes components are (i.e. kube-apiserver).

You can use https://github.com/openvswitch/ovn-kubernetes/tree/master/vagrant or https://github.com/openvswitch/ovn-kubernetes/tree/master/contrib to quickly setup a cluster.

You can look over: http://www.openvswitch.org/support/dist-docs/ovn-architecture.7.pdf, https://blog.russellbryant.net/2016/09/29/ovs-2-6-and-the-first-release-of-ovn/ too familiarise yourself a bit with OVN.
