### ISSUE TITLE
Logical port is down after creation

### ISSUE THREAD

**Issue by RostyslavFridman** [openvswitch/ovn-kubernetes#6]
I have the following vagrant setup.
1 node cluster with kubernetes master and openvswitch running on the same node. CLUSTER_IP_SUBNET=10.3.0.0/16, MASTER_SWITCH_SUBNET=10.3.1.0/24.
Everything have started and interfaces exist:
```
br-int: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::48d9:3bff:fedc:aa4c  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:06:b9:de  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 62  bytes 13666 (13.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:b7ff:fe5d:b203  prefixlen 64  scopeid 0x20<link>
        ether 02:42:b7:5d:b2:03  txqueuelen 0  (Ethernet)
        RX packets 3002  bytes 269534 (263.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3012  bytes 939730 (917.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fecb:cb16  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:cb:cb:16  txqueuelen 1000  (Ethernet)
        RX packets 433934  bytes 613898403 (585.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 114035  bytes 6555659 (6.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 20.0.0.1  netmask 255.255.255.0  broadcast 20.0.0.255
        inet6 fe80::a00:27ff:fe06:b9de  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:06:b9:de  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26  bytes 3211 (3.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.8.101  netmask 255.255.255.0  broadcast 172.17.8.255
        inet6 fe80::a00:27ff:fe59:e994  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:59:e9:94  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 27  bytes 3301 (3.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

k8s-172.17.8.10: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.3.1.2  netmask 255.255.255.0  broadcast 0.0.0.0
        ether c6:c1:8d:41:03:59  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 112 (112.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 35  bytes 10370 (10.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 69855  bytes 26598786 (25.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 69855  bytes 26598786 (25.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ovs-system: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::8013:f4ff:fe51:3a0f  prefixlen 64  scopeid 0x20<link>
        ether 82:13:f4:51:3a:0f  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 61  bytes 13334 (13.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

However, when I create new pod I see that logical port is down:
```
ovn-nbctl list logical_switch_port default_redis-master-2463511816-vaq6k
_uuid               : e078e54a-0534-4d6c-81da-a993796318a4
addresses           : [dynamic]
dhcpv4_options      : []
dhcpv6_options      : []
dynamic_addresses   : "0a:00:00:00:00:07 10.3.1.9"
enabled             : []
external_ids        : {}
name                : "default_redis-master-2463511816-vaq6k"
options             : {}
parent_name         : []
port_security       : []
tag                 : []
type                : ""
up                  : false
```

Moreover, pod is getting network configuration from docker0 bridge.

Have I missed something in documentation?
Thank you in advance for any help you can provide.

**Comment by shettyg** [comment]
@RostyslavFridman

The current documentation and code expects master to not run any containers.  There are multiple reasons for it - one of them being containers mucking around with the north-bound database. So you likely ran just the master-init? That script does not create a CNI plugin and hence the containers started will get IP addresses from docker bridge.

Btwn, thanks for trying it out. We still are a little poor with documentation (and a couple of bugs). I just noticed that there is no mention of how to start kubelet with the OVN CNI plugin.
It should be something like:

./kubelet --api-servers=http://10.33.74.22:8080 --v=2 --address=0.0.0.0 --enable-server=true --network-plugin=cni

**Comment by salv-orlando** [comment]
On that note, it should not be a big problem running pods on master as well.
I have indeed a 2 node setup where the kubelet is running also on the master node (mostly to save the hassle of using a 3rd vm to achieve a 2-node testbed).

To do so I think I ran both master-init and minion-init on the master, specifying the same subnet. If I recall correctly minion-init skipped the steps for creating the node ls and connecting it to the cluster lr as they were already performed by master-init, and simply configured the CNI plugin.

**Comment by RostyslavFridman** [comment]
It finally works.
Moreover, it is OK to run master-init and minion-init on the same node in the same subnet.

I've struggled mostly with running this solution on CoreOS when everything is containerized.
If anyone would like to repeat this, dockerized kubelet should contain cni binaries, openvswitch binaries and ovn-kubernetes scripts.

Thank you for the help.

**Comment by shettyg** [comment]
@RostyslavFridman 
It looks like you are familiar with both k8s and OVN to have got this working with coreos. One challenge of having CNI plugin running in master would be that the core daemons running inside containers will also get OVN private IP addresses?

**Comment by salv-orlando** [comment]
Which core daemons are you referring to?
I am not using coreos but on ubuntu I have no problem running the kubelet as well on the master node. I agree you probably should not be doing that in production, but in dev envs it gives you an extra node!

From what I recall the kubelet does not invoke network plugins for pods with special security context attributes such as hostnetwork.

**Comment by RostyslavFridman** [comment]
@shettyg
Actually running core daemons are not a big issue. They are running with `hostNetwork: true`, so they are getting host IP address and not OVN private IP addresses.
On the other hand, `kube-dns` and `kube-dashboard` are getting OVN private IP addresses.

Basically, what should be done is the following:
1. Create manifests for core services (`kube-apiserver.yml`, `kube-controller-manager.yml`, `kube-proxy.yml`, `kube-scheduler.yml`) and place them in `/etc/kubernetes/manifests` folder
2. Create a custom image on top of hyperkube one with openvswitch, cni and ovn-kubernetes installed
3. Run kubelet container with this configuration
```
/usr/bin/docker run -d \
    --net=host \
    --pid=host \
    --privileged \
    --restart=unless-stopped \
    --name kubelet \
    --volume /etc/cni/net.d:/etc/cni/net.d \
    --volume /etc/kubernetes:/etc/kubernetes \
    --volume /sys:/sys:rw \
    --volume /var/run:/var/run:rw \
    --volume /run:/run:rw \
    --volume /var/lib/docker:/var/lib/docker:rw \
    --volume /var/lib/kubelet:/var/lib/kubelet:shared \
    --volume /var/log/containers:/var/log/containers:rw \
    <custom_hyperkube_image>:v1.3.6 \
    /hyperkube kubelet \
      --allow-privileged \
      --api-servers=http://127.0.0.1:8080 \
      --config=/etc/kubernetes/manifests \
      --cluster-dns=<kube_dns_service_ip> \
      --cluster-domain=certascale.local \
      --network-plugin=cni \
      --network-plugin-dir=/etc/cni/net.d \
      --hostname-override=<eth_ip_address> \
      --v=2
```
_
4. Run ovs commands inside container:
```
docker exec kubelet /usr/share/openvswitch/scripts/ovs-ctl start

...

docker exec kubelet ovn-k8s-watcher --overlay
```

One caveat is that `/etc/cni/net.d` should contain some configuration file. It won't be used but it should be present.

Another one is that it is not a CoreOS suggested way of running kubernetes. They suggest to use `kubelet-wrapper`, but it runs kubelet in `rkt` and you won't be able to manage OVS in it.
