### ISSUE TITLE
onv-kubernetes should use kubeconfig file generated from its own service account.

### ISSUE THREAD

**Issue by pliurh** [openvswitch/ovn-kubernetes#602]
In ovnkube.sh, KUBECONFIG is hard coded to '/etc/origin/node/node.kubeconfig', which only exists in okd 3.x. And using it in a pod is more or less violating the RBAC of K8S. 

So instead of using that, I propose to generated  the kubeconfig file from ovn-kubernetes's own secrets in '/var/run/secrets/kubernetes.io/serviceaccount'.

**Comment by girishmg** [comment]
@shettyg @dcbw This issue can be closed since PR #605 takes care of it.
