### ISSUE TITLE
master must deal with pods being created before their node is ready

### ISSUE THREAD

**Issue by danwinship** [openvswitch/ovn-kubernetes#613]
The master is assuming that no non-hostNetwork pods will be scheduled on a node until after ovnkube on that node has fully registered itself. But this isn't quite true; a pod that tolerates `KubeletNotReady` can be *scheduled* to the node while ovnkube is still starting up, it just won't be able to get past `ContainerCreating` until ovnkube is ready. But when this happens, the ovnkube master tries to process the pod when it is first created, fails, and then ignores it afterward:

on the master:
```
level=error msg="Error while creating logical port openshift-kube-apiserver-operator_openshift-kube-apiserver-operator-89ffb44d6-7zllm stdout: \"\", stderr: \"ovn-nbctl: ip-10-0-36-247.us-east-2.compute.internal: switch name not found\\n\" (exit status 1)"
```
then later (repeatedly) on the node:
```
level=info msg="Waiting for ADD result for pod openshift-kube-apiserver-operator/openshift-kube-apiserver-operator-89ffb44d6-7zllm"
level=info msg="Dispatching pod network request &{ADD openshift-kube-apiserver-operator openshift-kube-apiserver-operator-89ffb44d6-7zllm 52b077e82cfa37e741524a1daa113a55ea14caf12137b49943a285f942dfd4c4 /proc/21526/ns/net eth0 0xc4204e2500 0xc4206c60c0}"
level=error msg="failed to get pod annotation - timed out waiting for the condition"
```

@dcbw

**Comment by oilbeater** [comment]
Maybe ovn-kubernetes should requeue failed addPod event

**Comment by dcbw** [comment]
I think this is actually a dupe of https://github.com/openvswitch/ovn-kubernetes/issues/531 ?

**Comment by danwinship** [comment]
indeed
