### ISSUE TITLE
Cannot execute make under Linux OS

### ISSUE THREAD

**Issue by ylhyh** [openvswitch/ovn-kubernetes#619]
Becuase of all the sh files under the folder "go-controller\hack" are stored in dos format. 
Execute make will occurs below error:
`-bash: hack/build-go.sh: /bin/bash^M: bad interpreter: No such file or directory`

Files should use unix line-ending

**Comment by shettyg** [comment]
We continuosly build under linux. So, something else is going on at your end. May be a fresh clone?
