### ISSUE TITLE
Cannot init node with "Error setting OVS external ID..."

### ISSUE THREAD

**Issue by ylhyh** [openvswitch/ovn-kubernetes#620]
I have follwoing the guide [HA.md](https://github.com/openvswitch/ovn-kubernetes/blob/master/docs/ha.md) to created an OVN cluster. 
Then execute
`ovnkube --init-master ...` to initlizized master with no error.

When I executing node initialization use ovnkube with the parameters below:
`sudo ovnkube --k8s-kubeconfig /etc/kubernetes/admin.conf \
--loglevel 4 \
--logfile "/var/log/openvswitch/ovnkube.log" \
--init-node="node001" \
--cluster-subnet="10.112.0.0/12" \
--service-cluster-ip-range="10.96.0.0/12" \
--init-gateways \
--nb-address="tcp://172.16.126.202:6641,tcp://172.16.126.203:6641,tcp://172.16.126.204:6641" \
--sb-address="tcp://172.16.126.202:6642,tcp://172.16.126.203:6642,tcp://172.16.126.204:6642"
`

I got an error to ask me to provide --k8s-token parameter even I have provided --k8s-kubeconfig parameter:
`panic: Cannot initialize node without service account 'token'. Please provide one with --k8s-token argument`

So I created a cluster-admin ServiceAccount and then pass the SA's token to ovnkube utility, it throw a new error:
```
panic: Error setting OVS external ID 'ovn-nb="tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641"': exit status 1
  ""

goroutine 1 [running]:
main.runOvnKube(0xc00049adc0, 0x0, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:267 +0xfac
main.main.func1(0xc00049adc0, 0xc00049adc0, 0xc00019181f)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x2b
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x10bd600, 0x12e8c30, 0xc00049adc0, 0xc0000e7980, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc00015ee00, 0xc00003a0f0, 0xf, 0xf, 0x0, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x5b7
main.main()
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0xa54
```
Can anyone help?

Any help or comment will be appreciated

**Comment by girishmg** [comment]
Setting up the ovn-nb key in Open_vSwitch's external_ids is literally one of the first things we do when bringing up onvkube in node mode. Can you check if ovsdb-server process is up and running on that node?

**Comment by ylhyh** [comment]
Thank you very mush @girishmg.
Yes, I forget to start openvswtich.service on the nodes. 

After I started the openvswitch.service and execute ovnkube --init-node again, all the kubernetes nodes get Ready.

Should I execute ovnkube --init-node on the Kubernetes MASTER nodes? NODE in ovn is meaning NETWORK NODE, not Kubernetes NODE, right?

**Comment by girishmg** [comment]
`ovnkube node` means the entity that needs to run on every kubernetes node. It creates OVN L3 gateways and that provide Internet/External network access to pods. Also, it provides the K8s service NodePort feature .

**Comment by ylhyh** [comment]
Thans again @girishmg.

I'm confusing between the two guide:
[](https://github.com/openvswitch/ovn-kubernetes/blob/master/README.md)
[](https://github.com/openvswitch/ovn-kubernetes/blob/master/docs/ha.md)

For HA OVN central database, should i follow HA guide to start nb_db/sb_db by the following scripts?
```
IP1="$MASTER1"
IP2="$MASTER2"
IP3="$MASTER3"

export ovn_nb="tcp:$IP1:6641,tcp:$IP2:6641,tcp:$IP3:6641"
export ovn_sb="tcp:$IP1:6642,tcp:$IP2:6642,tcp:$IP3:6642"

sudo ovn-northd -vconsole:emer -vsyslog:err -vfile:info \
    --ovnnb-db="$ovn_nb" --ovnsb-db="$ovn_sb" --no-chdir \
    --log-file=/var/log/openvswitch/ovn-northd.log \
    --pidfile=/var/run/openvswitch/ovn-northd.pid --detach --monitor
```

Or use /usr/share/openvswitch/scripts/ovn-ctl start_northd to start them?

I have met error  when using "ovn-northd -vconsole:emer -vsyslog:err -vfile:info .. " to start ovn-northd
