### ISSUE TITLE
Confused with the two guide

### ISSUE THREAD

**Issue by ylhyh** [openvswitch/ovn-kubernetes#621]
I'm confused with the two guide:
[How to use Open Virtual Networking with Kubernetes](https://github.com/openvswitch/ovn-kubernetes/blob/master/README.md)
[OVN central database High-availability](https://github.com/openvswitch/ovn-kubernetes/blob/master/docs/ha.md)

For HA OVN central database, should i follow HA guide to start nb_db/sb_db by the following scripts?
```
IP1="$MASTER1"
IP2="$MASTER2"
IP3="$MASTER3"

export ovn_nb="tcp:$IP1:6641,tcp:$IP2:6641,tcp:$IP3:6641"
export ovn_sb="tcp:$IP1:6642,tcp:$IP2:6642,tcp:$IP3:6642"

sudo ovn-northd -vconsole:emer -vsyslog:err -vfile:info \
    --ovnnb-db="$ovn_nb" --ovnsb-db="$ovn_sb" --no-chdir \
    --log-file=/var/log/openvswitch/ovn-northd.log \
    --pidfile=/var/run/openvswitch/ovn-northd.pid --detach --monitor
```

Or use /usr/share/openvswitch/scripts/ovn-ctl start_northd to start them?

I have met error  when using "ovn-northd -vconsole:emer -vsyslog:err -vfile:info .. " to start ovn-northd

Bu I can check the cluster status and it seems work normally after I following the ha.md to complete 
node initialization for Maste1/Master2/Master3 and then to use "/usr/share/openvswitch/scripts/ovn-ctl start_northd" to start db. 

Did't to execute the [start ovn-northd](https://github.com/openvswitch/ovn-kubernetes/blob/master/docs/ha.md#start-ovn-northd) step. 
Is the “start ovn-northd” step required? 
Or it duplicate to "/usr/share/openvswitch/scripts/ovn-ctl start_northd" in README.md?

```
# ovs-appctl -t /var/run/openvswitch/ovnnb_db.ctl cluster/status OVN_Northbound
adef
Name: OVN_Northbound
Cluster ID: 9ea7 (9ea742f6-e24c-4586-aead-d98156b77f67)
Server ID: adef (adef22c8-a443-4b1b-867c-3a5c8f95aff6)
Address: tcp:172.16.126.202:6643
Status: cluster member
Role: leader
Term: 1
Leader: self
Vote: self

Log: [2, 6]
Entries not yet committed: 0
Entries not yet applied: 0
Connections: <-48fe ->48fe <-2f05 ->2f05
Servers:
    adef (adef at tcp:172.16.126.202:6643) (self) next_index=2 match_index=5
    48fe (48fe at tcp:172.16.126.203:6643) next_index=6 match_index=5
    2f05 (2f05 at tcp:172.16.126.204:6643) next_index=6 match_index=5

```

```
# ovs-appctl -t /var/run/openvswitch/ovnnb_db.ctl cluster/status OVN_Southbound
89a6
Name: OVN_Southbound
Cluster ID: c1ec (c1ecb6bb-a076-4800-9c4e-4e42a8faa136)
Server ID: 89a6 (89a64c91-de7f-43e2-9698-0983814c99fd)
Address: tcp:172.16.126.202:6644
Status: cluster member
Role: leader
Term: 1
Leader: self
Vote: self

Log: [2, 5]
Entries not yet committed: 0
Entries not yet applied: 0
Connections: <-df2d ->df2d <-63d3 ->63d3
Servers:
    63d3 (63d3 at tcp:172.16.126.202:6644) next_index=5 match_index=4
    df2d (df2d at tcp:172.16.126.203:6644) next_index=5 match_index=4
    89a6 (89a6 at tcp:172.16.126.204:6644) (self) next_index=2 match_index=4

```

**Comment by shettyg** [comment]
You should start ovn-northd the way it asks to be started in HA guide.
