### ISSUE TITLE
Allow PODs on K8s nodes to access host IP when using Shared Gateway Interface

### ISSUE THREAD

**Issue by girishmg** [openvswitch/ovn-kubernetes#632]
We have a significant drawback while deploying K8s cluster using OVN-K8s CNI in Shared gateway interface mode. In this mode,

1. one cannot deploy a POD on the K8s Master node. The PODs requiring K8s API Server access  ends up in CrashLoopBackOff as it cannot reach K8s API Server through the kubernetes Service IP (10.96.0.1:443). This happens because 10.96.0.1 is translated to the K8s Master host IP and this IP cannot be accessed from the OVN logical topology since this same IP address is used by OVN L3 gateway. 

2. an another issue is that a POD on a host cannot access any service on that host itself. For example: a `metrics-server` POD on a host H1 that wants to access the stats from kubelet running on that host at port 10250, will fail

This is because the packets from the POD meant for the host on which it resides gets dropped in `lr_in_unsnat` table in the L3 gateway router pipeline. 

The solution to this problem is to add an host route to the OVN cluster router (ovn_cluster_router) for every host through its management port. For example: In a 3-node K8s cluster (Master, Node1, Node2), we will do the following:
```
 ovn-nbctl lr-route-add ovn_cluster_router MasterIP k8s-Master
 ovn-nbctl lr-route-add ovn_cluster_router Node1 k8s-node1
 ovn-nbctl lr-route-add ovn_cluster_router Node2 k8s-node2
```

These routes should allow the packets meant for the host to exit out through the management logical switch port on that logical_switch. This should solve the issues (1) and (2) above

Please see the following document for more information and solution:
https://docs.google.com/document/d/17X55J7XEhwtOntD1M_ldIdeZqHioq41f9tWJM29O3Rg/edit?usp=sharing

**Comment by girishmg** [comment]
@shettyg @dcbw can you guys please comment on the proposal above? This is more serious than I initially thought since there is an another situation where in the shared gateway interface creates an issue.

**Comment by shettyg** [comment]
>These routes should allow the packets meant for the host to exit out through the management logical switch port on that logical_switch. This should solve the issues (1) and (2) above

Have you tried this? (Should work, but the loopback needed to go back to switch only works in certain ciscumstances and I don't remember them all).

>ovn-nbctl lr-route-add ovn_cluster_router MasterIP k8s-Master

1. Does this assume that kube-apiserver is also listening in k8s-Master? Is that a valid assumption?

2. Will not the above effect pods in nodes? i.e when they have destination IP as MasterIP, the nexthop is k8s-Master. So does the packet jump to master via geneve tunnels without going through gateways?

>ovn-nbctl lr-route-add ovn_cluster_router Node1 k8s-node1
 ovn-nbctl lr-route-add ovn_cluster_router Node2 k8s-node2

Why do you need the above routes?

**Comment by girishmg** [comment]
> > These routes should allow the packets meant for the host to exit out through the management logical switch port on that logical_switch. This should solve the issues (1) and (2) above
> 
> Have you tried this? (Should work, but the loopback needed to go back to switch only works in certain ciscumstances and I don't remember them all).

Yes, I have tried this and it works. This approach fixes both the issues we
have in our logical topology today. However, there is one additional step
(please read towards the end).

> 
> > ovn-nbctl lr-route-add ovn_cluster_router MasterIP k8s-Master
> 
>     1. Does this assume that kube-apiserver is also listening on k8s-Master IP. i.e 0.0.0.0? Is that a valid assumption?

The packet's destination IP is not modified (there is no DNAT). It will
still be the advertised K8s API server address. We are just forwarding the
packets to the management port as the next hop.

> 
>     2. Will not the above effect pods in nodes? i.e when they have destination IP as MasterIP, the nexthop is k8s-Master. So does the packet jump to master via geneve tunnels without going through gateways?

Yes. All the pods on the K8s Master node that needs access to K8s API server
through 10.96.0.1 (which will be converted to k8s-apiserver IP through LB)
will now go through the GENEVE tunnel.

> 
> 
> > ovn-nbctl lr-route-add ovn_cluster_router Node1 k8s-node1
> > ovn-nbctl lr-route-add ovn_cluster_router Node2 k8s-node2
> 
> Why do you need the above routes?

We have another problem in our logical topology. Say, you have a pod on a
host and this pod wants to connect to the host's IP to pull some stat. For
example: There is this project
https://github.com/kubernetes-incubator/metrics-server that creates a POD
which pulls stats from kubelet at port 10250. It walks through all the
nodes in the k8s cluster and pulls stat from 10250. Now, back to our
example, our pod cannot pull stats from the Node on which it is
scheduled. The packet gets dropped in lr_in_unsnat in the L3 Gateway router
pipeline. The above routes will help such pods which need access to the node
on which they are scheduled. 

Note: In addition to the above static routes, we need to set arp_announce
to 1 on the k8s-`hostname` management ports. Without this setting, packets
from the pod to the node reach fine, but the replies from the node to the pod will not
work. This is because the ARP requests from the node towards the pod gets
dropped in lr_in_arp_response table of the ovn_cluster_router. The ARP
request has arp.spa set to K8s node IP, however OVN logical flows expect
the ARP queries to have source protocol address from the OVN logical subnet.
Setting arp_announce to 1 will ensure that the Linux Kernel will pick the source
protocol address to that of the interface on which the ARP queries are sent.

**Comment by shettyg** [comment]
@girishmg 

Sounds good to me.
