### ISSUE TITLE
[Ansible] Master /etc/hosts doesn't always include all minion nodes.

### ISSUE THREAD

**Issue by adelina-t** [openvswitch/ovn-kubernetes#637]
These lines in the playbook:

https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/ovn-kubernetes-cluster.yml#L91-L95 

Don't necessarily work as intended all the time. In some cases, the /etc/hosts file on the master node will contain only one of the linux / windows minions.

There is an issue open in the ansible repo about this behaviour of the lineinfile module: https://github.com/ansible/ansible/issues/30413

As far as I can see, there is a pending PR to fix this in ansible: https://github.com/ansible/ansible/pull/47322

**Comment by adelina-t** [comment]
@alinbalutoiu @aserdean

**Comment by alinbalutoiu** [comment]
Thanks for reporting the issue. I've sent a PR which will run the task serially one at a time to avoid the concurrency issues. Would be great if you could try that out.

**Comment by aserdean** [comment]
Closed via: https://github.com/openvswitch/ovn-kubernetes/pull/638
