### ISSUE TITLE
why is ovs-kubernetes implemented in python?

### ISSUE THREAD

**Issue by alpha-li** [openvswitch/ovn-kubernetes#64]
It seems that this project has nothing to do with openstack, so why using python stack. With python, there is so much dependences to be solved, with golang , only one binary file is OK. So I can not find any advantages to use python over golang. Anybody can answer this question? Thank you!

**Comment by shettyg** [comment]
2 reasons:

1. When we started this project, one of the goals was to integrate with OpenStack APIs. And since all OpenStack helper libraries are Python, Python was easier to start with.  Now, it looks like OpenStack Kuyr will do that part of the integration, so the reasoning is no longer valid.

2. official OVSDB bindings are available in C and Python. OVS also has many helper libraries in python. Though, we currently do not use OVSDB bindings for python, the transition would be easier.

Using golang has many advantages.

1. We can reuse a lot of libraries that kube-proxy already uses.
2. Obvious errors will be caught  while compiling.

**Comment by russellb** [comment]
For golang, I've seen this ovsdb library used, but have not looked closely at it myself: https://github.com/socketplane/libovsdb

**Comment by shettyg** [comment]
>For golang, I've seen this ovsdb library used, but have not looked closely at it myself: https://github.com/socketplane/libovsdb

From what I understand, it does not support a few OVSDB features that Python does. We will have to pick it and make it full feature.

**Comment by salv-orlando** [comment]
> It seems that this project has nothing to do with openstack, so why using python stack
There are plenty of python projects that have nothing to do with OpenStack (or that OpenStack uses but have a happy life outside of OpenStack)
Moreover, as @shettyg mentioned, initially we were looking at integrating with OVN via Openstack networking.

> So I can not find any advantages to use python over golang
Indeed there is probably no advantage. In the choice of the programming language for a project there are technical and non-technical considerations. Among the non-technical considerations there could be constraints (such as OpenStack accepting only python atm) and human factors.
I personally believe human factors played a role here, as it is fair to state that when the project was started initial contributors were more familiar with python than golang.

**Comment by alpha-li** [comment]
Thank you, guys. So whether it is possible or is there any plan to reimplement in golang?

**Comment by RostyslavFridman** [comment]
There is an issue when using libovsdb. All the constraints that are provided within ovs-vsctl tool should be implemented manually. For example, ovn-kubernetes relies heavily on uniqueness of switch and router names, but this is not the case for golang lib. I was able to create multiple switches with the same name.

**Comment by shettyg** [comment]
>Thank you, guys. So whether it is possible or is there any plan to reimplement in golang?

The short term goal is to get a full feature, stable integration and we are not going to attempt moving to golang, unless we start facing problems that would be solved by going to golang.

Over the long term, if there are performance issues with Python or it becomes a maintenance headache, golang is an option.  But the first step before anything is to get golang bindings for OVSDB - which I am not aware of anyone working on.
