### ISSUE TITLE
src-ip based routes take precedence and breaks NodePort

### ISSUE THREAD

**Issue by girishmg** [openvswitch/ovn-kubernetes#647]
Say, the cluster network cidr is 192.168.0.0/16 and that we have three node
k8s cluster. All the nodes are assigned with /24 prefixlen subnet. Following
static routes will be added to the OVN Cluster Router

```
$ ovn-nbctl lr-route-list ovn_cluster_router
IPv4 Routes
           192.168.3.0/24                100.64.0.2 src-ip
           192.168.4.0/24                100.64.0.4 src-ip
           192.168.5.0/24                100.64.0.3 src-ip
                0.0.0.0/0                100.64.0.2 dst-ip
```

Following, logical flows will be added by ovn-northd for ovn_cluster_router

```
$ ovn-sbctl lflow-list ovn_cluster_router |grep  lr_in_ip_routing |cut -f3,4 -d,

1. match=(ip4.src == 192.168.3.0/24), action=(ip.ttl--; reg0 = 100.64.0.2; reg1 = 100.64.0.1; eth.src = 00:00:00:ac:bf:ed;...)
2. match=(ip4.src == 192.168.4.0/24), action=(ip.ttl--; reg0 = 100.64.0.4; reg1 = 100.64.0.1; eth.src = 00:00:00:ac:bf:ed;...)
3. match=(ip4.src == 192.168.5.0/24), action=(ip.ttl--; reg0 = 100.64.0.3; reg1 = 100.64.0.1; eth.src = 00:00:00:ac:bf:ed;...)
4. match=(ip4.dst == 100.64.0.0/16), action=(ip.ttl--; reg0 = ip4.dst; reg1 = 100.64.0.1; eth.src = 00:00:00:ac:bf:ed;...)
5. match=(ip4.dst == 0.0.0.0/0), action=(ip.ttl--; reg0 = 100.64.0.2; reg1 = 100.64.0.1; eth.src = 00:00:00:ac:bf:ed;...)
```

In the above output, logical flows 1, 2, 3, and 5 reflect the corresponding
static routes from the lr-route-list above.

Logical flow 4, due to longest prefix match, gets pushed down in favor of the
src-ip based routes.

This causes an issue for NodePort, and this has existed all along. However,
with the move to /16 subnet for join logical switch the issue has become more
promininent

Path of a NodePort packet:
```
A packet to a NodePort hits the L3 gateway, say with IP 100.64.0.2, and gets
Load Balanced and is forced SNAT'ed to that IP. The packet arrives at the POD
(on another Node) and is serviced. On its return path, the destination IP now
is 100.64.0.2. Instead of making its way to the L3 gateway where it got
SNAT'ed, it will hit the src-ip based static routes (longest match prefix) and
will be forwarded to the wrong L3 gateway. Things start fo fail.
```
Fix:
```
The fix is to add a /32 static route to each of the lb_force_snat_ip IP
addresses. For example: In the above case,

ovn-nbctl lr-route-add ovn_cluster_router 100.64.0.2 100.64.0.2
ovn-nbctl lr-route-add ovn_cluster_router 100.64.0.3 100.64.0.3
ovn-nbctl lr-route-add ovn_cluster_router 100.64.0.4 100.64.0.4
```

**Comment by shettyg** [comment]
>This causes an issue for NodePort, and this has existed all along. However,
with the move to /16 subnet for join logical switch the issue has become more
promininent

Can you explain this a little more. I remember thinking about this and then coming to the conclusion that it will work fine (can't remember why. May be because 100.64.0.2 is a OVN IP and it will always have higher priority). Does this work when 100.64.0.0 is a /24 subnet? If so, why?

**Comment by girishmg** [comment]
@shettyg from ovn-nb(5) manpage we have

```
       When  multiple  routes match a packet, the longest-prefix match is cho‐
       sen. For a given prefix length, a dst-ip  route  is  preferred  over  a
       src-ip route.
```

For a given set of static routes the longest-prefix match has precedence and then for the same given prefix length dst-ip has precedence. Now with 100.64.0.0/24 and all the K8s node subnet having /24,  the prefix length is same and  since dst-ip is preferred over src-ip the reply packets from the POD with destination IP set to forced-SNAT LB IP, we will always hit 100.64.0.0/24 route and packets are forwarded to the right next hop.

Note that if the join subnet is 100.64.0.0/24 and the deployment selected the cluster network CIDR to be 192.168.0.0/16/28, then each of the node will have /28 and since the prefix length is longer than the 100.64.0.0./24 the src-ip route will be preferred and NodePort will not work.

**Comment by shettyg** [comment]
okay.
