### ISSUE TITLE
handling of external IPs must be made configurable

### ISSUE THREAD

**Issue by girishmg** [openvswitch/ovn-kubernetes#653]
We should make handling of external IPs configurable. If a deployment chooses to implement kubernetes service with external IP set using a Hardware or Software based load balancer, then the deployer will take care of mapping external IP to set of Node ports on the load balancer. We don't want ovnkube-master to configure OVN LB rules for external IPs for type=LoadBalancer.

**Comment by girishmg** [comment]
@shettyg What I meant during the call was that we need to handle External IPs only for NodePort and ClusterIP service. In the case of type LoadBalancer, the expectation is that the deployer works with GCP, AWS, or other cloud provider or uses any of the software/hardware based LB to implement that service.

OVN-k8s should not, at this point, claim to support LoadBalancer as it cannot.

**Comment by shettyg** [comment]
>What I meant during the call was that we need to handle External IPs only for NodePort and ClusterIP service.

Fair.

**Comment by girishmg** [comment]
fixed by #660
