### ISSUE TITLE
Add documentation about SSL connectivity to OVN databases

### ISSUE THREAD

**Issue by shettyg** [openvswitch/ovn-kubernetes#66]
This needs good documentation.

**Comment by salv-orlando** [comment]
Yup, it took me a while to figure out why ovsdb connections weren't working anymore after pulling from master. The commit msg for the ovsdb change is however pretty self-explanatory.

**Comment by RostyslavFridman** [comment]
Adding link to commit, for others who encounter this issue, because I spent couple of hours to find it several days ago https://github.com/openvswitch/ovs/commit/84d0ca5d00fe01b29163236d48fa0f9105687149

**Comment by shettyg** [comment]
#71 should fix this.
