### ISSUE TITLE
NodePort does not work properly for gateway-localnet

### ISSUE THREAD

**Issue by cathy-zhou** [openvswitch/ovn-kubernetes#667]
Assuming a kuberenetes cluster with ovn CNI, and a nodePort service is created:
# kubectl get svc
  ...
 web          NodePort    10.102.35.46    <none>        80:30838/TCP   90s

Accessing the nodePod service only succeeds if one tries to access the service through <node1_IP>:30838 from node1 locally. Trying to access <node1_IP>:30838 from outside of node1 fails. 

Further investigation reveals that we need to add the following IP nat rules on each node to allow nodePort to work properly:

  iptables -t nat -I PREROUTING -p tcp --dport 30838 -j DNAT --to-destination 169.254.33.2:30838
  iptables -t nat -I PREROUTING -p tcp --dport 30838 -j KUBE-MARK-MASQ

(The second rule is needed because the existing ip table rules).

So a potential fix is to let ovnkube-node to keep adding these rules for every new NodePort service.

**Comment by shettyg** [comment]
Is kube-proxy running?

**Comment by cathy-zhou** [comment]
Yes, it is running. I believe it is kube-proxy that added a ip table rule of equivalent of:

   iptables -t nat -I PREROUTING -p tcp --dport 30838 -j DNAT --to-destination 192.168.4.3:5000

where 192.168.4.3:5000 is the service POD IP and port. But that does not work.

**Comment by girishmg** [comment]
@shettyg we want the external traffic to NodePort to go through the L3 gateway and not through the K8s Management port. This causes issue in the return path.

**Comment by shettyg** [comment]
@girishmg 

I see. I thought you had submitted a patch to avoid using gateway localnet?

**Comment by girishmg** [comment]
@shettyg  My fixes have been with the shared-interface-gateway mode. We still support br-localnet (this should really be br-local). However, this is broken for Nodeport. We will need a fix where-in for every NodePort service we will add an iptable rule like @cathy-zhou suggests.

Also, it is good to fix this. With that fix we will not need kube-proxy to run for all the 3 modes of gateway we support.

**Comment by shettyg** [comment]
Fair.
