### ISSUE TITLE
Internal port mac addresses can change when rebooting

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovn-kubernetes#88]
The internal port used for management should add also the MAC address in the interface scripts:
https://github.com/openvswitch/ovn-kubernetes/blob/ae4ecfb2d323fc3eb2e0b5f0611d19dbbe2630c0/bin/ovn-k8s-overlay#L116-L123

The issue is during reboot the interface MAC address will change and OVN will not pick it up.

CC: @pires

**Comment by shettyg** [comment]
That was subtle. I will provide a fix.

**Comment by pires** [comment]
Let us know when you open the PR @shettyg! Thanks a ton.

**Comment by shettyg** [comment]
I have a pull request ready for this fix.
