### ISSUE TITLE
vagrant scripts no longer work as intended

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovn-kubernetes#89]
OVS recently changed version. Meaning the following lines are inconsistent:

https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-minion.sh#L51-L54
https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-master.sh#L47-L51

We could change from 2.6.90-1 to 2.7.90-1 but we should make it use a variable i.e. the one defined in the automake build chain.

**Comment by shettyg** [comment]
You are right. I think, we can just use * for a simpler fix. I will provide a fix.

**Comment by shettyg** [comment]
#93 Should fix it.
