### ISSUE TITLE
MTU should be configurable

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovn-kubernetes#91]
Different setups will have different specifications, having the MTU configurable via a config file(or a given parameter) could help the end user.

https://github.com/openvswitch/ovn-kubernetes/blob/ae4ecfb2d323fc3eb2e0b5f0611d19dbbe2630c0/bin/ovn-k8s-overlay#L284
https://github.com/openvswitch/ovn-kubernetes/blob/a16e91fa3f9f26d8413e55a28500cbd572970f37/bin/ovn-k8s-cni-overlay#L106

**Comment by shettyg** [comment]
If you are using overlay networks with Geneve, the last time I calculated, it came to around 1443. But if someone adds more Geneve options in OVN, it will decrease. But I see your point. Some people may have underlay at 9000 and in that case, you don't need this. I guess, we can default to 1400, but people can pass it as an option.

**Comment by shettyg** [comment]
This is configurable now.
