### ISSUE TITLE
Vagrant: apiserver fails to come up on k8s-master

### ISSUE THREAD

**Issue by akashgangil** [openvswitch/ovn-kubernetes#97]
F0305 19:27:42.990716    3331 controller.go:128] Unable to perform initial IP allocation check: unable to refresh the service IP block: client: etcd cluster is unavailable or misconfigured

Looks like etcd docker container failed to start. Since this worked on manual startup.

I didn't run vagrant up in debug mode, so don't have the provisioning logs.

**Comment by shettyg** [comment]
Is it consistent or was it a one off thing? I haven't seen this happen and I do bring up a vagrant environment very often. But vagrants are tricky and it is hard to pinpoint why something did not work unless you debug it.

**Comment by fkautz** [comment]
There might be some aggressive timeouts or a race condition. I noticed on slower systems that some services fail to come up but have no problems spinning up vagrant on faster systems.
